// lms-frontend/src/views/analytics/AuditAnalytics.vue
<script setup lang="ts">
import AppSidebar from '@/components/layout/AppSidebar.vue'
</script>

<template>
  <div class="flex h-screen bg-gray-50 overflow-hidden font-sans text-sm">
    <AppSidebar />
    <main class="flex-1 overflow-y-auto">
      <header class="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between sticky top-0 z-10">
        <h1 class="font-bold text-primary text-xl">Laporan Audit & Assessment</h1>
        <div class="w-8 h-8 rounded-full bg-secondary text-white flex items-center justify-center font-bold text-sm">B</div>
      </header>
      <div class="p-4 md:p-8 flex items-center justify-center h-[calc(100vh-80px)]">
        <div class="text-center text-gray-400">
          <i class="pi pi-chart-bar text-4xl mb-4 block"></i>
          <p>Halaman laporan audit sedang dalam pengembangan.</p>
        </div>
      </div>
    </main>
  </div>
</template>

// frontend/src/views/analytics/AuditAnalytics.tsx
import React from 'react';
import { BarChart3, Construction } from 'lucide-react';

export const AuditAnalytics: React.FC = () => {
  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2.5">
          <BarChart3 className="w-6 h-6 text-[#419CC3]" /> Laporan Audit & Assessment
        </h1>
        <p className="text-slate-500 text-sm mt-1">
          Pantau ringkasan kepatuhan dan temuan inspeksi lapangan.
        </p>
      </div>

      <div className="bg-white rounded-2xl border border-slate-200 p-16 flex flex-col items-center justify-center text-center shadow-xs">
        <div className="w-16 h-16 bg-emerald-50 text-emerald-600 rounded-2xl flex items-center justify-center mb-4">
          <Construction className="w-8 h-8" />
        </div>
        <h3 className="text-lg font-bold text-slate-800">Modul Sedang Dalam Pengembangan</h3>
        <p className="text-sm text-slate-500 max-w-sm mt-1">
          Laporan agregasi skor inspeksi dan breakdown temuan outlet akan tampil di sini.
        </p>
      </div>
    </div>
  );
};
