// lms-frontend/src/views/audit/ChecklistBuilder.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import AppSidebar from '@/components/layout/AppSidebar.vue';

const categories = ref<any[]>([]);
const isLoading = ref(true);

const fetchChecklists = async () => {
  isLoading.value = true;
  try {
    const res = await fetch('http://localhost:3000/audit/checklist');
    const data = await res.json();
    if (data.success) {
      categories.value = data.data;
    }
  } catch (error) {
    console.error('Failed to load checklists', error);
  } finally {
    isLoading.value = false;
  }
};

const saveChecklists = async () => {
  try {
    const res = await fetch('http://localhost:3000/audit/checklist/sync', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ categories: categories.value })
    });
    const data = await res.json();
    if (data.success) {
      alert('Berhasil menyimpan checklist!');
      categories.value = data.data; // update with true IDs from DB
    }
  } catch (error) {
    console.error('Failed to save', error);
    alert('Gagal menyimpan checklist');
  }
};

const addCategory = () => {
  categories.value.push({
    name: 'Kategori Baru',
    checklists: []
  });
};

const removeCategory = (index: number) => {
  if (confirm('Yakin ingin menghapus kategori ini?')) {
    categories.value.splice(index, 1);
  }
};

const addPoint = (catIndex: number) => {
  if (!categories.value[catIndex].checklists) {
    categories.value[catIndex].checklists = [];
  }
  categories.value[catIndex].checklists.push({
    question: 'Pertanyaan Baru'
  });
};

const removePoint = (catIndex: number, pointIndex: number) => {
  categories.value[catIndex].checklists.splice(pointIndex, 1);
};

onMounted(fetchChecklists);
</script>

<template>
  <div class="flex h-screen bg-gray-50 overflow-hidden font-sans text-sm">
    <AppSidebar />
    <main class="flex-1 overflow-y-auto">
      <header class="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between sticky top-0 z-10">
        <div>
          <h1 class="font-bold text-gray-800 text-xl">Kriteria Checklist Audit</h1>
          <p class="text-xs text-gray-500">Atur kategori dan poin pemeriksaan untuk inspeksi lapangan</p>
        </div>
        <Button label="Simpan Perubahan" icon="pi pi-save" @click="saveChecklists" />
      </header>
      
      <div class="p-6 md:p-8 max-w-5xl mx-auto space-y-6">
        <div v-if="isLoading" class="text-center p-12 text-gray-500">
          <i class="pi pi-spin pi-spinner text-4xl mb-4 text-primary"></i>
          <p>Memuat data checklist...</p>
        </div>
        <div v-else class="space-y-6">
          
          <div v-if="categories.length === 0" class="text-center p-12 bg-white border border-dashed border-gray-300 rounded-lg">
            <i class="pi pi-inbox text-4xl text-gray-300 mb-2"></i>
            <p class="text-gray-500 mb-4">Belum ada kriteria checklist yang dibuat.</p>
            <Button label="Buat Kategori Pertama" icon="pi pi-plus" @click="addCategory" />
          </div>

          <div v-for="(cat, cIdx) in categories" :key="cIdx" class="bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden">
            <div class="bg-gray-50 px-4 py-3 border-b border-gray-200 flex items-center gap-4">
              <i class="pi pi-bars text-gray-400 cursor-move"></i>
              <InputText v-model="cat.name" class="font-bold flex-1" placeholder="Nama Kategori (Contoh: Kebersihan Area Kasir)" />
              <Button icon="pi pi-trash" severity="danger" text @click="removeCategory(cIdx)" />
            </div>
            
            <div class="p-4 space-y-3">
              <div v-if="!cat.checklists || cat.checklists.length === 0" class="text-sm text-gray-400 italic">
                Belum ada poin pemeriksaan di kategori ini.
              </div>
              
              <div v-for="(point, pIdx) in cat.checklists" :key="pIdx" class="flex items-center gap-3">
                <i class="pi pi-list text-gray-300 cursor-move text-xs"></i>
                <InputText v-model="point.question" class="flex-1" placeholder="Contoh: Lantai bersih dan bebas sampah" />
                <Button icon="pi pi-times" severity="danger" text rounded @click="removePoint(cIdx, pIdx)" />
              </div>
              
              <Button label="Tambah Poin" icon="pi pi-plus" size="small" outlined class="mt-2" @click="addPoint(cIdx)" />
            </div>
          </div>
          
          <div v-if="categories.length > 0" class="text-center pt-4">
            <Button label="Tambah Kategori Baru" icon="pi pi-plus-circle" severity="secondary" @click="addCategory" />
          </div>
          
        </div>
      </div>
    </main>
  </div>
</template>

// frontend/src/views/audit/ChecklistBuilder.tsx
import React, { useState, useEffect } from 'react';
import {
  CheckSquare,
  Plus,
  Trash2,
  X,
  Save,
  Loader2,
  GripVertical,
  List,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardHeader, CardContent } from '@/components/ui/card';
import { PageHeader } from '@/components/common/PageHeader';
import { EmptyState } from '@/components/common/EmptyState';
import { getApiUrl } from '@/lib/api';

interface ChecklistItem {
  id?: string;
  question: string;
}

interface Category {
  id?: string;
  name: string;
  checklists: ChecklistItem[];
}

export const ChecklistBuilder: React.FC = () => {
  const [categories, setCategories] = useState<Category[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  const fetchChecklists = async () => {
    setIsLoading(true);
    try {
      const res = await fetch(getApiUrl('/audit/checklist'));
      const data = await res.json();
      if (data.success) {
        setCategories(data.data || []);
      }
    } catch (err) {
      console.error('Failed to load checklists', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSaveChecklists = async () => {
    setIsSaving(true);
    try {
      const res = await fetch(getApiUrl('/audit/checklist/sync'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ categories }),
      });
      const data = await res.json();
      if (data.success) {
        alert('Berhasil menyimpan checklist audit!');
        setCategories(data.data || []);
      } else {
        alert('Gagal menyimpan checklist');
      }
    } catch (err) {
      console.error('Failed to save', err);
      alert('Terjadi kesalahan saat menyimpan.');
    } finally {
      setIsSaving(false);
    }
  };

  const addCategory = () => {
    setCategories([
      ...categories,
      {
        name: 'Kategori Baru',
        checklists: [],
      },
    ]);
  };

  const removeCategory = (index: number) => {
    if (window.confirm('Yakin ingin menghapus kategori ini?')) {
      setCategories(categories.filter((_, i) => i !== index));
    }
  };

  const addPoint = (catIndex: number) => {
    const updated = [...categories];
    if (!updated[catIndex].checklists) {
      updated[catIndex].checklists = [];
    }
    updated[catIndex].checklists.push({
      question: 'Pertanyaan Baru',
    });
    setCategories(updated);
  };

  const removePoint = (catIndex: number, pointIndex: number) => {
    const updated = [...categories];
    updated[catIndex].checklists.splice(pointIndex, 1);
    setCategories(updated);
  };

  const updateCategoryName = (catIndex: number, name: string) => {
    const updated = [...categories];
    updated[catIndex].name = name;
    setCategories(updated);
  };

  const updatePointQuestion = (catIndex: number, pointIndex: number, question: string) => {
    const updated = [...categories];
    updated[catIndex].checklists[pointIndex].question = question;
    setCategories(updated);
  };

  useEffect(() => {
    fetchChecklists();
  }, []);

  return (
    <div className="p-6 md:p-8 max-w-5xl mx-auto space-y-6">
      {/* Reusable Page Header */}
      <PageHeader
        title="Kriteria Checklist Audit"
        subtitle="Atur kategori dan poin pemeriksaan untuk inspeksi lapangan (Audit App)"
        icon={<CheckSquare className="w-7 h-7" />}
        actions={
          <Button
            onClick={handleSaveChecklists}
            disabled={isSaving}
            className="bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold flex items-center gap-2 shadow-sm"
          >
            {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
            Simpan Perubahan
          </Button>
        }
      />

      {isLoading ? (
        <div className="text-center py-16">
          <Loader2 className="w-8 h-8 animate-spin mx-auto text-[#419CC3] mb-3" />
          <p className="text-sm text-slate-500">Memuat data checklist audit...</p>
        </div>
      ) : (
        <div className="space-y-6">
          {categories.length === 0 ? (
            <EmptyState
              title="Belum ada kriteria checklist"
              description="Buat kategori dan tentukan poin-poin pertanyaan audit untuk toko."
              actionLabel="Buat Kategori Pertama"
              onAction={addCategory}
              actionIcon={<Plus className="w-4 h-4" />}
            />
          ) : (
            categories.map((cat, cIdx) => (
              <Card key={cIdx} className="rounded-2xl border-slate-200 shadow-sm overflow-hidden">
                {/* Category Header */}
                <CardHeader className="bg-slate-50 px-5 py-3.5 border-b border-slate-200 flex flex-row items-center gap-3">
                  <GripVertical className="w-4 h-4 text-slate-400" />
                  <Input
                    value={cat.name}
                    onChange={(e) => updateCategoryName(cIdx, e.target.value)}
                    placeholder="Nama Kategori (Contoh: Kebersihan Area Kasir)"
                    className="font-bold text-sm bg-white flex-1"
                  />
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => removeCategory(cIdx)}
                    className="text-slate-400 hover:text-rose-500 hover:bg-rose-50"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </CardHeader>

                {/* Points List */}
                <CardContent className="p-5 space-y-3">
                  {(!cat.checklists || cat.checklists.length === 0) && (
                    <p className="text-xs text-slate-400 italic">
                      Belum ada poin pemeriksaan di kategori ini.
                    </p>
                  )}

                  {cat.checklists?.map((point, pIdx) => (
                    <div key={pIdx} className="flex items-center gap-2.5">
                      <List className="w-4 h-4 text-slate-300 shrink-0" />
                      <Input
                        value={point.question}
                        onChange={(e) => updatePointQuestion(cIdx, pIdx, e.target.value)}
                        placeholder="Contoh: Lantai bersih dan bebas sampah"
                        className="text-sm flex-1 bg-slate-50/50"
                      />
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => removePoint(cIdx, pIdx)}
                        className="text-slate-400 hover:text-rose-500 hover:bg-rose-50 rounded-full h-8 w-8"
                      >
                        <X className="w-4 h-4" />
                      </Button>
                    </div>
                  ))}

                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => addPoint(cIdx)}
                    className="mt-2 text-xs font-bold text-[#419CC3] border-slate-200"
                  >
                    <Plus className="w-3.5 h-3.5 mr-1" /> Tambah Poin
                  </Button>
                </CardContent>
              </Card>
            ))
          )}

          {categories.length > 0 && (
            <div className="text-center pt-2">
              <Button
                variant="outline"
                onClick={addCategory}
                className="font-bold text-slate-700 border-slate-300"
              >
                <Plus className="w-4 h-4 mr-2" /> Tambah Kategori Baru
              </Button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
