// lms-frontend/src/views/audit/OutletManagement.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import Button from 'primevue/button';
import Tag from 'primevue/tag';
import AppSidebar from '@/components/layout/AppSidebar.vue';

const outlets = ref([]);
const loading = ref(false);
const syncing = ref(false);

const fetchOutlets = async () => {
  loading.value = true;
  try {
    const res = await fetch('http://localhost:3000/audit/outlets');
    if (res.ok) {
      outlets.value = await res.json();
    }
  } catch (error) {
    console.error('Error fetching outlets:', error);
  } finally {
    loading.value = false;
  }
};

const syncHRIS = async () => {
  syncing.value = true;
  try {
    const res = await fetch('http://localhost:3000/audit/outlets/sync-hris', { method: 'POST' });
    const data = await res.json();
    if (res.ok && data.success) {
      alert(data.message);
      await fetchOutlets();
    } else {
      alert(data.message || 'Gagal sinkronisasi HRIS.');
    }
  } catch (error) {
    console.error('Error syncing:', error);
    alert('Tidak dapat terhubung ke Backend NestJS atau Backend gagal menghubungi Server HRIS (Pastikan Server HRIS berjalan di Port 8000).');
  } finally {
    syncing.value = false;
  }
};

onMounted(() => {
  fetchOutlets();
});
</script>

<template>
  <div class="flex h-screen bg-gray-50 overflow-hidden font-sans text-sm">
    <AppSidebar />
    <main class="flex-1 overflow-y-auto">
      <div class="p-6 md:p-8 max-w-7xl mx-auto space-y-6">
        <!-- Header -->
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 class="text-2xl font-bold text-gray-800">Manajemen Outlet</h1>
            <p class="text-gray-500 mt-1">Kelola data outlet (toko) yang terintegrasi dari HRIS</p>
          </div>
          <div class="flex gap-2">
            <Button 
              @click="syncHRIS" 
              :loading="syncing" 
              icon="pi pi-sync" 
              label="Sync dari HRIS" 
              severity="info" 
            />
            <Button 
              icon="pi pi-plus" 
              label="Tambah Manual" 
              severity="primary" 
              outlined
            />
          </div>
        </div>

        <!-- Data Table -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          <DataTable :value="outlets" :loading="loading" paginator :rows="10" 
                     dataKey="id" class="p-datatable-sm" 
                     emptyMessage="Belum ada data outlet. Klik 'Sync dari HRIS' untuk menyedot data terbaru.">
            
            <Column field="name" header="Nama Outlet" sortable></Column>
            <Column field="device_code" header="Kode Perangkat (HRIS)" sortable></Column>
            <Column field="device_name" header="Nama Perangkat"></Column>
            <Column field="address" header="Alamat" style="max-width: 300px; white-space: normal;">
              <template #body="{ data }">
                <span class="text-xs text-gray-600">{{ data.address || '-' }}</span>
              </template>
            </Column>
            <Column header="Status">
              <template #body="{ data }">
                <Tag :severity="data.status === 'active' ? 'success' : 'danger'" 
                     :value="data.status === 'active' ? 'Aktif' : 'Non-aktif'" />
              </template>
            </Column>
          </DataTable>
        </div>
      </div>
    </main>
  </div>
</template>

<style scoped>
/* Optional styling overrides for PrimeVue */
:deep(.p-datatable .p-datatable-thead > tr > th) {
  background-color: #f8fafc;
  color: #475569;
  font-weight: 700;
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  padding: 1rem;
}
:deep(.p-datatable .p-datatable-tbody > tr > td) {
  padding: 1rem;
  border-bottom: 1px solid #f1f5f9;
}
</style>

// frontend/src/views/audit/OutletManagement.tsx
import React from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Store, RefreshCw, Plus, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHeader } from '@/components/common/PageHeader';
import { DataTable, ColumnDef } from '@/components/common/DataTable';
import { StatusBadge } from '@/components/common/StatusBadge';
import { getApiUrl } from '@/lib/api';

interface Outlet {
  id: string;
  name: string;
  device_code?: string;
  device_name?: string;
  address?: string;
  status: 'active' | 'inactive';
}

export const OutletManagement: React.FC = () => {
  const queryClient = useQueryClient();

  const { data: outlets = [], isLoading } = useQuery<Outlet[]>({
    queryKey: ['outlets'],
    queryFn: async () => {
      const res = await fetch(getApiUrl('/audit/outlets'));
      if (!res.ok) throw new Error('Failed to load outlets');
      return res.json();
    },
  });

  const syncMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(getApiUrl('/audit/outlets/sync-hris'), {
        method: 'POST',
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Gagal sinkronisasi Outlet HRIS.');
      }
      return data;
    },
    onSuccess: (data) => {
      alert(data.message || 'Sinkronisasi Outlet HRIS selesai!');
      queryClient.invalidateQueries({ queryKey: ['outlets'] });
    },
    onError: (err: any) => {
      alert(err.message || 'Gagal menghubungi Backend NestJS atau Server HRIS.');
    },
  });

  const columns: ColumnDef<Outlet>[] = [
    {
      key: 'name',
      header: 'Nama Outlet',
      sortable: true,
      render: (row) => <span className="font-bold text-slate-800">{row.name}</span>,
    },
    {
      key: 'device_code',
      header: 'Kode Perangkat (HRIS)',
      sortable: true,
      render: (row) => (
        <span className="font-mono text-xs text-slate-500 font-semibold">
          {row.device_code || '-'}
        </span>
      ),
    },
    {
      key: 'device_name',
      header: 'Nama Perangkat',
      render: (row) => <span className="text-slate-600">{row.device_name || '-'}</span>,
    },
    {
      key: 'address',
      header: 'Alamat',
      render: (row) => (
        <span className="text-xs text-slate-500 max-w-[280px] block truncate">
          {row.address || '-'}
        </span>
      ),
    },
    {
      key: 'status',
      header: 'Status',
      align: 'center',
      render: (row) => <StatusBadge status={row.status} />,
    },
  ];

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-6">
      {/* Reusable Page Header */}
      <PageHeader
        title="Manajemen Outlet"
        subtitle="Kelola data outlet (toko) yang terintegrasi dari HRIS"
        icon={<Store className="w-7 h-7" />}
        actions={
          <>
            <Button
              onClick={() => syncMutation.mutate()}
              disabled={syncMutation.isPending}
              className="bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold flex items-center gap-2 shadow-sm"
            >
              {syncMutation.isPending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <RefreshCw className="w-4 h-4" />
              )}
              Sync dari HRIS
            </Button>
            <Button
              variant="outline"
              className="font-bold flex items-center gap-2 border-slate-200"
            >
              <Plus className="w-4 h-4" /> Tambah Manual
            </Button>
          </>
        }
      />

      {/* Reusable Data Table */}
      <DataTable
        data={outlets}
        columns={columns}
        isLoading={isLoading}
        searchPlaceholder="Cari nama toko, kode perangkat, atau alamat..."
        emptyMessage="Belum ada data outlet. Klik 'Sync dari HRIS' untuk menyedot data terbaru."
      />
    </div>
  );
};
