// frontend/src/views/sop/SopManagement.tsx
import React, { useState, useRef } from 'react';
import { FileText, Sparkles, CheckCircle2, Upload, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { PageHeader } from '@/components/common/PageHeader';
import { getApiUrl } from '@/lib/api';

export const SopManagement: React.FC = () => {
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('HEAD_OFFICE');
  const [isUploading, setIsUploading] = useState(false);
  const [uploadSuccess, setUploadSuccess] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const file = fileInputRef.current?.files?.[0];
    if (!file) {
      alert('Pilih file PDF SOP terlebih dahulu.');
      return;
    }

    setIsUploading(true);
    setUploadSuccess(false);

    const formData = new FormData();
    formData.append('title', title);
    formData.append('category', category);
    formData.append('file', file);

    try {
      const res = await fetch(getApiUrl('/api/sop/upload'), {
        method: 'POST',
        body: formData,
      });

      if (res.ok) {
        setUploadSuccess(true);
        setTitle('');
        setCategory('HEAD_OFFICE');
        if (fileInputRef.current) fileInputRef.current.value = '';
      } else {
        alert('Gagal mengunggah SOP.');
      }
    } catch (err) {
      console.error(err);
      alert('Terjadi kesalahan saat menghubungi server.');
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="p-6 md:p-8 max-w-4xl mx-auto space-y-6">
      {/* Reusable Page Header */}
      <PageHeader
        title="Manajemen SOP (Admin)"
        subtitle="Unggah dokumen SOP dalam format PDF. Sistem AI akan mengekstrak butir-butir panduan secara otomatis."
        icon={<FileText className="w-7 h-7" />}
      />

      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 md:p-8">
        <form onSubmit={handleSubmit} className="space-y-5">
          <div className="space-y-1.5">
            <label className="text-xs font-bold text-slate-700 uppercase">Judul SOP</label>
            <Input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Contoh: SOP Kasir & Pelayanan Pelanggan"
              required
            />
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-bold text-slate-700 uppercase">Kategori</label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full h-10 rounded-md border border-slate-200 bg-white px-3 py-1 text-sm shadow-xs focus:outline-hidden focus:ring-1 focus:ring-[#419CC3]"
            >
              <option value="HEAD_OFFICE">Head Office</option>
              <option value="OPERASIONAL">Operasional (Outlet)</option>
            </select>
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-bold text-slate-700 uppercase">File PDF SOP</label>
            <div className="border-2 border-dashed border-slate-200 rounded-xl p-6 text-center hover:bg-slate-50 transition-colors">
              <input
                type="file"
                ref={fileInputRef}
                accept="application/pdf"
                className="hidden"
                id="sop-file-input"
                required
              />
              <label
                htmlFor="sop-file-input"
                className="cursor-pointer flex flex-col items-center justify-center gap-1.5"
              >
                <Upload className="w-8 h-8 text-slate-400" />
                <span className="text-sm font-bold text-[#419CC3]">
                  Pilih Dokumen PDF SOP
                </span>
                <span className="text-xs text-slate-400">Format .pdf maksimal 10MB</span>
              </label>
            </div>
          </div>

          <Button
            type="submit"
            disabled={isUploading}
            className="w-full bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold h-11 shadow-md flex items-center justify-center gap-2"
          >
            {isUploading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" /> Sedang Mengunggah & Mengekstrak AI...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" /> Upload & Ekstrak AI
              </>
            )}
          </Button>
        </form>

        {uploadSuccess && (
          <div className="mt-6 p-4 bg-emerald-50 text-emerald-800 border border-emerald-200 rounded-xl flex items-center gap-3">
            <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0" />
            <div>
              <h4 className="font-bold text-sm">Berhasil Diunggah!</h4>
              <p className="text-xs text-emerald-700 mt-0.5">
                SOP telah diekstrak oleh AI dan siap dibaca oleh seluruh tim di Pustaka SOP.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// lms-frontend/src/views/sop/SopManagement.vue
<template>
  <div class="flex h-screen bg-gray-50 overflow-hidden font-sans text-sm">
    <AppSidebar />
    <main class="flex-1 overflow-y-auto bg-gray-50/50">
      
      <!-- Top Mobile Nav (Hidden on Desktop) -->
      <div class="md:hidden bg-white p-4 border-b border-gray-200 flex justify-between items-center sticky top-0 z-10">
        <h1 class="font-bold text-primary">TND SYSTEM</h1>
        <div class="w-8 h-8 rounded-full bg-secondary text-white flex items-center justify-center font-bold text-sm">B</div>
      </div>

      <div class="p-6 md:p-8 space-y-6 max-w-7xl mx-auto">
        <div class="flex justify-between items-center mb-6">
          <h1 class="text-xl font-bold text-gray-800">Manajemen SOP (Admin)</h1>
        </div>

        <div class="bg-white rounded-lg shadow-sm border border-gray-100 p-6 max-w-2xl">
          <form @submit.prevent="uploadSop" class="space-y-6">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Judul SOP</label>
              <InputText v-model="form.title" class="w-full rounded-lg" placeholder="Contoh: SOP Kasir Outlet" required />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Kategori</label>
              <Select v-model="form.category" :options="categories" optionLabel="label" optionValue="value" placeholder="Pilih Kategori" class="w-full rounded-lg" required />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">File PDF SOP</label>
              <input type="file" ref="fileInput" accept="application/pdf" class="block w-full text-sm text-gray-500
                file:mr-4 file:py-2 file:px-4
                file:rounded-lg file:border-0
                file:text-sm file:font-semibold
                file:bg-[#89B4E1] file:text-white
                hover:file:brightness-95 cursor-pointer
              " required />
              <p class="text-xs text-gray-500 mt-2">Sistem AI akan mengekstrak panduan dari PDF ini secara otomatis.</p>
            </div>

            <div class="pt-4 border-t border-gray-100">
              <Button type="submit" :loading="isUploading" label="Upload & Ekstrak AI" icon="pi pi-sparkles" class="w-full bg-primary border-primary rounded-lg text-white font-bold py-3" />
            </div>
          </form>

          <div v-if="uploadSuccess" class="mt-6 p-4 bg-emerald-50 text-emerald-600 border border-emerald-100 rounded-lg flex items-center gap-3">
            <i class="pi pi-check-circle text-xl"></i>
            <div>
              <h3 class="font-bold">Berhasil Diunggah!</h3>
              <p class="text-sm">SOP telah diekstrak oleh AI dan siap dibaca oleh tim.</p>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import InputText from 'primevue/inputtext';
import Select from 'primevue/select';
import Button from 'primevue/button';
import AppSidebar from '@/components/layout/AppSidebar.vue';

const form = ref({
  title: '',
  category: ''
});

const categories = [
  { label: 'Head Office', value: 'HEAD_OFFICE' },
  { label: 'Operasional (Outlet)', value: 'OPERASIONAL' }
];

const fileInput = ref<HTMLInputElement | null>(null);
const isUploading = ref(false);
const uploadSuccess = ref(false);

const uploadSop = async () => {
  const file = fileInput.value?.files?.[0];
  if (!file) return;

  isUploading.value = true;
  uploadSuccess.value = false;

  const formData = new FormData();
  formData.append('title', form.value.title);
  formData.append('category', form.value.category);
  formData.append('file', file);

  try {
    const res = await fetch('http://localhost:3001/api/sop/upload', {
      method: 'POST',
      body: formData
    });
    
    if (res.ok) {
      uploadSuccess.value = true;
      form.value.title = '';
      form.value.category = '';
      if (fileInput.value) fileInput.value.value = '';
    }
  } catch (error) {
    console.error('Upload failed:', error);
    alert('Gagal mengunggah SOP.');
  } finally {
    isUploading.value = false;
  }
};
</script>
