// frontend/src/components/quiz/QuizBuilder.tsx
import React, { useState } from 'react';
import { PlusCircle, Trash2, CheckCircle2, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { DynamicInputList, OptionItem } from '@/components/ui/DynamicInputList';

interface Question {
  id: string;
  text: string;
  type: 'MULTIPLE_CHOICE' | 'MULTIPLE_ANSWER' | 'TRUE_FALSE';
  options: OptionItem[];
}

const generateId = () => Math.random().toString(36).substring(2, 9);

export const QuizBuilder: React.FC = () => {
  const [passingScore, setPassingScore] = useState(80);
  const [certificateTemplateId, setCertificateTemplateId] = useState('');

  const [questions, setQuestions] = useState<Question[]>([
    {
      id: generateId(),
      text: '',
      type: 'MULTIPLE_CHOICE',
      options: [
        { text: '', is_correct: true },
        { text: '', is_correct: false },
        { text: '', is_correct: false },
        { text: '', is_correct: false },
      ],
    },
  ]);

  const addQuestion = () => {
    setQuestions([
      ...questions,
      {
        id: generateId(),
        text: '',
        type: 'MULTIPLE_CHOICE',
        options: [
          { text: '', is_correct: true },
          { text: '', is_correct: false },
        ],
      },
    ]);
  };

  const removeQuestion = (index: number) => {
    setQuestions(questions.filter((_, i) => i !== index));
  };

  const updateQuestion = (index: number, updated: Partial<Question>) => {
    setQuestions(
      questions.map((q, i) => (i === index ? { ...q, ...updated } : q))
    );
  };

  const handleSave = () => {
    const payload = {
      passing_score: passingScore,
      certificate_template_id: certificateTemplateId,
      questions,
    };
    console.log('Quiz Payload:', payload);
    alert('Kuis berhasil disimpan! (Payload JSON dicatat pada console)');
  };

  return (
    <div className="max-w-4xl mx-auto py-4 space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Quiz Builder</h1>
          <p className="text-slate-500 text-sm mt-1">
            Buat soal kuis dan tentukan kunci jawaban untuk modul pelatihan.
          </p>
        </div>
        <Button
          onClick={handleSave}
          className="bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold flex items-center gap-2 shadow-sm"
        >
          <Save className="w-4 h-4" /> Simpan Kuis
        </Button>
      </div>

      {/* Main Settings */}
      <Card className="rounded-2xl border-slate-200 shadow-sm">
        <CardHeader className="pb-3 border-b border-slate-100 bg-slate-50/50">
          <CardTitle className="text-base font-bold text-slate-800">
            Pengaturan Utama
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <label className="text-xs font-bold text-slate-700 uppercase">
              Nilai Minimal Kelulusan (Passing Score)
            </label>
            <Input
              type="number"
              min={0}
              max={100}
              value={passingScore}
              onChange={(e) => setPassingScore(Number(e.target.value))}
              className="bg-white"
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-bold text-slate-700 uppercase">
              Template Sertifikat
            </label>
            <select
              value={certificateTemplateId}
              onChange={(e) => setCertificateTemplateId(e.target.value)}
              className="w-full h-9 rounded-md border border-slate-200 bg-white px-3 py-1 text-sm shadow-xs focus:outline-hidden focus:ring-1 focus:ring-[#419CC3]"
            >
              <option value="">Tidak ada sertifikat</option>
              <option value="template-1">Sertifikat Kelulusan Standar</option>
            </select>
          </div>
        </CardContent>
      </Card>

      {/* Questions */}
      <div className="space-y-4">
        {questions.map((q, qIndex) => (
          <Card key={q.id} className="rounded-2xl border-slate-200 shadow-sm overflow-hidden">
            <CardHeader className="py-3 px-5 border-b border-slate-100 bg-slate-50/60 flex flex-row items-center justify-between">
              <div className="flex items-center gap-3">
                <span className="w-7 h-7 rounded-full bg-slate-200 text-slate-700 font-bold text-xs flex items-center justify-center">
                  {qIndex + 1}
                </span>
                <select
                  value={q.type}
                  onChange={(e) =>
                    updateQuestion(qIndex, {
                      type: e.target.value as Question['type'],
                    })
                  }
                  className="text-xs font-semibold bg-white border border-slate-200 rounded-lg px-2.5 py-1.5 shadow-xs"
                >
                  <option value="MULTIPLE_CHOICE">Pilihan Ganda (1 Jawaban)</option>
                  <option value="MULTIPLE_ANSWER">Pilihan Ganda (Banyak Jawaban)</option>
                  <option value="TRUE_FALSE">Benar / Salah</option>
                </select>
              </div>

              {questions.length > 1 && (
                <button
                  type="button"
                  onClick={() => removeQuestion(qIndex)}
                  className="text-slate-400 hover:text-rose-500 p-1.5 rounded-lg hover:bg-rose-50 transition-colors"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              )}
            </CardHeader>

            <CardContent className="p-5 space-y-4">
              <div className="space-y-1">
                <label className="text-xs font-bold text-slate-700 uppercase">
                  Teks Pertanyaan
                </label>
                <Textarea
                  value={q.text}
                  onChange={(e) => updateQuestion(qIndex, { text: e.target.value })}
                  placeholder="Tulis pertanyaan di sini..."
                  rows={2}
                  className="resize-none text-sm"
                />
              </div>

              <div className="space-y-1">
                <label className="text-xs font-bold text-slate-700 uppercase">
                  Pilihan Jawaban
                </label>
                <DynamicInputList
                  value={q.options}
                  onChange={(options) => updateQuestion(qIndex, { options })}
                  type={q.type}
                />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Add Question Button */}
      <button
        type="button"
        onClick={addQuestion}
        className="w-full py-4 border-2 border-dashed border-slate-300 hover:border-[#419CC3] hover:bg-[#419CC3]/5 rounded-2xl text-slate-500 hover:text-[#419CC3] font-bold text-sm transition-all flex flex-col items-center justify-center gap-1 cursor-pointer"
      >
        <PlusCircle className="w-5 h-5" />
        Tambah Pertanyaan Baru
      </button>
    </div>
  );
};

// lms-frontend/src/components/quiz/QuizBuilder.vue
<template>
  <div class="max-w-4xl mx-auto py-8">
    <div class="mb-8 flex justify-between items-end">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Quiz Builder</h1>
        <p class="text-gray-500 mt-1">Buat soal kuis dan atur kunci jawaban untuk modul ini.</p>
      </div>
      <button 
        @click="saveQuiz"
        class="bg-primary hover:bg-primary/90 text-white px-6 py-2.5 rounded-lg font-medium transition-colors shadow-sm"
      >
        Simpan Kuis
      </button>
    </div>

    <!-- Quiz Settings -->
    <Card class="mb-8">
      <template #header>
        <h2 class="text-lg font-semibold text-gray-800">Pengaturan Utama</h2>
      </template>
      <div class="grid grid-cols-2 gap-6">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Nilai Minimal Kelulusan (Passing Score)</label>
          <input 
            v-model="quizConfig.passing_score"
            type="number" 
            min="0" max="100"
            class="w-full border-gray-300 rounded-lg shadow-sm focus:ring-primary focus:border-primary"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Template Sertifikat Kelulusan</label>
          <select 
            v-model="quizConfig.certificate_template_id"
            class="w-full border-gray-300 rounded-lg shadow-sm focus:ring-primary focus:border-primary"
          >
            <option value="">Tidak ada sertifikat</option>
            <!-- In a real app, populate from API -->
            <option value="template-1">Sertifikat Kelulusan Standar</option>
          </select>
        </div>
      </div>
    </Card>

    <!-- Questions List -->
    <div class="space-y-6">
      <Card v-for="(q, qIndex) in questions" :key="q.id">
        <template #header>
          <div class="flex items-center gap-3">
            <span class="bg-gray-100 text-gray-600 w-8 h-8 rounded-full flex items-center justify-center font-semibold text-sm">
              {{ qIndex + 1 }}
            </span>
            <select 
              v-model="q.type"
              class="border-gray-200 bg-gray-50 text-sm rounded-lg focus:ring-primary focus:border-primary py-1.5"
            >
              <option value="MULTIPLE_CHOICE">Pilihan Ganda (1 Jawaban)</option>
              <option value="MULTIPLE_ANSWER">Pilihan Ganda (Banyak Jawaban)</option>
              <option value="TRUE_FALSE">Benar / Salah</option>
            </select>
          </div>
          <button 
            @click="removeQuestion(qIndex)"
            class="text-red-500 hover:text-red-600 p-1 rounded hover:bg-red-50"
            title="Hapus Soal"
          >
            <span class="material-symbols-outlined text-[20px]">delete</span>
          </button>
        </template>

        <!-- Question Text -->
        <div class="mb-4">
          <textarea 
            v-model="q.text"
            rows="2"
            placeholder="Tulis pertanyaan di sini..."
            class="w-full border-gray-300 rounded-lg shadow-sm focus:ring-primary focus:border-primary resize-none"
          ></textarea>
        </div>

        <!-- Options Builder -->
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-2">Pilihan Jawaban</label>
          <DynamicInputList 
            v-model="q.options"
            :type="q.type"
          />
        </div>
      </Card>
    </div>

    <!-- Add Question Button -->
    <button 
      @click="addQuestion"
      class="w-full mt-6 py-4 border-2 border-dashed border-gray-300 rounded-xl text-gray-500 font-medium hover:bg-gray-50 hover:border-gray-400 transition-colors flex flex-col items-center gap-1"
    >
      <span class="material-symbols-outlined">add_circle</span>
      Tambah Pertanyaan Baru
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Card from '../ui/Card.vue'
import DynamicInputList from '../ui/DynamicInputList.vue'
import type { OptionItem } from '../ui/DynamicInputList.vue'

// Define Question Type
interface Question {
  id: string
  text: string
  type: 'MULTIPLE_CHOICE' | 'MULTIPLE_ANSWER' | 'TRUE_FALSE'
  options: OptionItem[]
}

const generateId = () => Math.random().toString(36).substring(2, 9)

const quizConfig = ref({
  passing_score: 80,
  certificate_template_id: ''
})

const questions = ref<Question[]>([
  {
    id: generateId(),
    text: '',
    type: 'MULTIPLE_CHOICE',
    options: [
      { text: '', is_correct: true },
      { text: '', is_correct: false },
      { text: '', is_correct: false },
      { text: '', is_correct: false }
    ]
  }
])

const addQuestion = () => {
  questions.value.push({
    id: generateId(),
    text: '',
    type: 'MULTIPLE_CHOICE',
    options: [
      { text: '', is_correct: true },
      { text: '', is_correct: false }
    ]
  })
}

const removeQuestion = (index: number) => {
  questions.value.splice(index, 1)
}

const saveQuiz = () => {
  const payload = {
    ...quizConfig.value,
    questions: questions.value
  }
  
  // Here we would typically call the API (e.g. POST /api/lms/quizzes)
  console.log('Saving Quiz Draft Payload:', payload)
  alert('Kuis berhasil disimpan! (Silakan cek Console Log untuk melihat struktur JSON API)')
}
</script>
