// frontend/src/components/layout/AppSidebar.tsx
import React, { useState } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import {
  LayoutDashboard,
  FolderOpen,
  Users,
  CheckSquare,
  BarChart3,
  FileText,
  Building2,
  LogOut,
  ChevronDown,
} from 'lucide-react';
import {
  Sidebar,
  SidebarHeader,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarMenuSub,
  SidebarMenuSubItem,
  SidebarMenuSubButton,
  SidebarRail,
} from '@/components/animate-ui/components/radix/sidebar';
import { cn } from '@/lib/utils';

export const AppSidebar: React.FC = () => {
  const location = useLocation();

  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    audit: true,
    analytics: true,
    sop: true,
  });

  const toggleSection = (key: string) => {
    setExpandedSections((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  const isPathActive = (path?: string) => {
    if (!path) return false;
    return location.pathname === path;
  };

  return (
    <Sidebar collapsible="icon" className="border-r border-slate-200 bg-white">
      {/* Header */}
      <SidebarHeader className="p-3 border-b border-slate-100 flex items-center justify-between group-data-[collapsible=icon]:p-2 group-data-[collapsible=icon]:justify-center">
        <div className="flex items-center gap-2.5 min-w-0">
          <div className="w-8 h-8 bg-[#419CC3]/10 text-[#419CC3] rounded-lg flex items-center justify-center font-bold shrink-0">
            <Building2 className="w-4 h-4" />
          </div>
          <div className="flex flex-col min-w-0 group-data-[collapsible=icon]:hidden">
            <h1 className="font-bold text-xs text-slate-800 tracking-tight truncate leading-tight">
              TND LMS
            </h1>
            <p className="text-[10px] text-slate-400 font-medium truncate">
              Learning & Audit
            </p>
          </div>
        </div>
      </SidebarHeader>

      {/* Content */}
      <SidebarContent className="custom-scrollbar px-2 py-3 space-y-2 group-data-[collapsible=icon]:px-1.5 group-data-[collapsible=icon]:py-2">
        {/* Main Navigation */}
        <SidebarGroup className="group-data-[collapsible=icon]:p-0">
          <SidebarGroupLabel className="text-[10px] font-bold tracking-wider uppercase text-slate-400 px-2 group-data-[collapsible=icon]:hidden">
            Menu Utama
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu className="space-y-1">
              {/* Beranda Dasbor */}
              <SidebarMenuItem>
                <SidebarMenuButton
                  asChild
                  isActive={isPathActive('/dashboard')}
                  tooltip="Dasbor"
                  className={cn(
                    'font-medium text-xs px-2.5 py-2 rounded-lg transition-colors duration-150',
                    isPathActive('/dashboard')
                      ? 'bg-[#419CC3]/10 text-[#419CC3] font-bold'
                      : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                  )}
                >
                  <NavLink to="/dashboard" className="flex items-center gap-2.5 overflow-hidden">
                    <LayoutDashboard className="w-4 h-4 text-slate-500 shrink-0" />
                    <span className="truncate group-data-[collapsible=icon]:hidden">Dasbor</span>
                  </NavLink>
                </SidebarMenuButton>
              </SidebarMenuItem>

              {/* Pustaka Materi */}
              <SidebarMenuItem>
                <SidebarMenuButton
                  asChild
                  isActive={isPathActive('/library')}
                  tooltip="Pustaka Materi"
                  className={cn(
                    'font-medium text-xs px-2.5 py-2 rounded-lg transition-colors duration-150',
                    isPathActive('/library')
                      ? 'bg-[#419CC3]/10 text-[#419CC3] font-bold'
                      : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                  )}
                >
                  <NavLink to="/library" className="flex items-center gap-2.5 overflow-hidden">
                    <FolderOpen className="w-4 h-4 text-slate-500 shrink-0" />
                    <span className="truncate group-data-[collapsible=icon]:hidden">Pustaka Materi</span>
                  </NavLink>
                </SidebarMenuButton>
              </SidebarMenuItem>

              {/* Manajemen Karyawan */}
              <SidebarMenuItem>
                <SidebarMenuButton
                  asChild
                  isActive={isPathActive('/employees')}
                  tooltip="Manajemen Karyawan"
                  className={cn(
                    'font-medium text-xs px-2.5 py-2 rounded-lg transition-colors duration-150',
                    isPathActive('/employees')
                      ? 'bg-[#419CC3]/10 text-[#419CC3] font-bold'
                      : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                  )}
                >
                  <NavLink to="/employees" className="flex items-center gap-2.5 overflow-hidden">
                    <Users className="w-4 h-4 text-slate-500 shrink-0" />
                    <span className="truncate group-data-[collapsible=icon]:hidden">Manajemen Karyawan</span>
                  </NavLink>
                </SidebarMenuButton>
              </SidebarMenuItem>
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        {/* Audit Group */}
        <SidebarGroup className="group-data-[collapsible=icon]:p-0">
          <SidebarGroupLabel className="text-[10px] font-bold tracking-wider uppercase text-slate-400 px-2 group-data-[collapsible=icon]:hidden">
            Sistem Audit
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu className="space-y-1">
              <SidebarMenuItem>
                <SidebarMenuButton
                  onClick={() => toggleSection('audit')}
                  tooltip="Sistem Audit"
                  className="font-medium text-xs px-2.5 py-2 rounded-lg text-slate-600 hover:bg-slate-50 flex items-center justify-between transition-colors duration-150 overflow-hidden"
                >
                  <div className="flex items-center gap-2.5 overflow-hidden">
                    <CheckSquare className="w-4 h-4 text-slate-500 shrink-0" />
                    <span className="truncate group-data-[collapsible=icon]:hidden">Audit Lapangan</span>
                  </div>
                  <ChevronDown
                    className={cn(
                      'w-3.5 h-3.5 text-slate-400 transition-transform duration-200 group-data-[collapsible=icon]:hidden shrink-0',
                      expandedSections.audit ? 'rotate-0' : '-rotate-90'
                    )}
                  />
                </SidebarMenuButton>

                {expandedSections.audit && (
                  <SidebarMenuSub className="ml-4 border-l border-slate-200 pl-2 space-y-1 pt-1 group-data-[collapsible=icon]:hidden">
                    <SidebarMenuSubItem>
                      <SidebarMenuSubButton asChild isActive={isPathActive('/outlets')}>
                        <NavLink to="/outlets">Manajemen Outlet</NavLink>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                    <SidebarMenuSubItem>
                      <SidebarMenuSubButton asChild isActive={isPathActive('/checklist-builder')}>
                        <NavLink to="/checklist-builder">Kriteria Checklist</NavLink>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                    <SidebarMenuSubItem>
                      <SidebarMenuSubButton asChild isActive={isPathActive('/audit-reports')}>
                        <NavLink to="/audit-reports">Laporan Inspeksi</NavLink>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                  </SidebarMenuSub>
                )}
              </SidebarMenuItem>
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        {/* Analytics Group */}
        <SidebarGroup className="group-data-[collapsible=icon]:p-0">
          <SidebarGroupLabel className="text-[10px] font-bold tracking-wider uppercase text-slate-400 px-2 group-data-[collapsible=icon]:hidden">
            Analytics
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu className="space-y-1">
              <SidebarMenuItem>
                <SidebarMenuButton
                  onClick={() => toggleSection('analytics')}
                  tooltip="Analytics & Laporan"
                  className="font-medium text-xs px-2.5 py-2 rounded-lg text-slate-600 hover:bg-slate-50 flex items-center justify-between transition-colors duration-150 overflow-hidden"
                >
                  <div className="flex items-center gap-2.5 overflow-hidden">
                    <BarChart3 className="w-4 h-4 text-slate-500 shrink-0" />
                    <span className="truncate group-data-[collapsible=icon]:hidden">Laporan & Evaluasi</span>
                  </div>
                  <ChevronDown
                    className={cn(
                      'w-3.5 h-3.5 text-slate-400 transition-transform duration-200 group-data-[collapsible=icon]:hidden shrink-0',
                      expandedSections.analytics ? 'rotate-0' : '-rotate-90'
                    )}
                  />
                </SidebarMenuButton>

                {expandedSections.analytics && (
                  <SidebarMenuSub className="ml-4 border-l border-slate-200 pl-2 space-y-1 pt-1 group-data-[collapsible=icon]:hidden">
                    <SidebarMenuSubItem>
                      <SidebarMenuSubButton asChild isActive={isPathActive('/analytics/leaderboard')}>
                        <NavLink to="/analytics/leaderboard">Papan Peringkat (XP)</NavLink>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                    <SidebarMenuSubItem>
                      <SidebarMenuSubButton asChild isActive={isPathActive('/analytics/quiz-history')}>
                        <NavLink to="/analytics/quiz-history">Riwayat Kuis</NavLink>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                    <SidebarMenuSubItem>
                      <SidebarMenuSubButton asChild isActive={isPathActive('/analytics/audit')}>
                        <NavLink to="/analytics/audit">Laporan Audit Outlet</NavLink>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                  </SidebarMenuSub>
                )}
              </SidebarMenuItem>
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>

        {/* SOP Group */}
        <SidebarGroup className="group-data-[collapsible=icon]:p-0">
          <SidebarGroupLabel className="text-[10px] font-bold tracking-wider uppercase text-slate-400 px-2 group-data-[collapsible=icon]:hidden">
            SOP & Prosedur
          </SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu className="space-y-1">
              <SidebarMenuItem>
                <SidebarMenuButton
                  onClick={() => toggleSection('sop')}
                  tooltip="Standar Operasional"
                  className="font-medium text-xs px-2.5 py-2 rounded-lg text-slate-600 hover:bg-slate-50 flex items-center justify-between transition-colors duration-150 overflow-hidden"
                >
                  <div className="flex items-center gap-2.5 overflow-hidden">
                    <FileText className="w-4 h-4 text-slate-500 shrink-0" />
                    <span className="truncate group-data-[collapsible=icon]:hidden">Pustaka SOP</span>
                  </div>
                  <ChevronDown
                    className={cn(
                      'w-3.5 h-3.5 text-slate-400 transition-transform duration-200 group-data-[collapsible=icon]:hidden shrink-0',
                      expandedSections.sop ? 'rotate-0' : '-rotate-90'
                    )}
                  />
                </SidebarMenuButton>

                {expandedSections.sop && (
                  <SidebarMenuSub className="ml-4 border-l border-slate-200 pl-2 space-y-1 pt-1 group-data-[collapsible=icon]:hidden">
                    <SidebarMenuSubItem>
                      <SidebarMenuSubButton asChild isActive={isPathActive('/sop/viewer')}>
                        <NavLink to="/sop/viewer">Daftar SOP</NavLink>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                    <SidebarMenuSubItem>
                      <SidebarMenuSubButton asChild isActive={isPathActive('/sop/management')}>
                        <NavLink to="/sop/management">Unggah Dokumen</NavLink>
                      </SidebarMenuSubButton>
                    </SidebarMenuSubItem>
                  </SidebarMenuSub>
                )}
              </SidebarMenuItem>
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>

      {/* Footer */}
      <SidebarFooter className="p-2.5 border-t border-slate-100 bg-slate-50/40 flex flex-row items-center justify-between group-data-[collapsible=icon]:justify-center group-data-[collapsible=icon]:p-2">
        <div className="flex items-center gap-2.5 min-w-0 group-data-[collapsible=icon]:hidden">
          <div className="w-7 h-7 rounded-lg bg-[#419CC3] text-white flex items-center justify-center font-bold text-xs shrink-0">
            BS
          </div>
          <div className="min-w-0">
            <p className="text-xs font-bold text-slate-800 truncate">Budi Santoso</p>
            <p className="text-[10px] text-slate-400 truncate">Instruktur</p>
          </div>
        </div>

        <NavLink
          to="/login"
          title="Keluar"
          className="text-slate-400 hover:text-rose-500 p-1.5 rounded-lg hover:bg-slate-100 transition-colors shrink-0"
        >
          <LogOut className="w-4 h-4" />
        </NavLink>
      </SidebarFooter>

      <SidebarRail />
    </Sidebar>
  );
};

// lms-frontend/src/components/layout/AppSidebar.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';

const router = useRouter();
const route = useRoute();

const menu = ref([
  {
    label: 'Beranda Dasbor',
    icon: 'pi pi-home',
    path: '/dashboard'
  },
  {
    label: 'Manajemen Kursus',
    icon: 'pi pi-book',
    expanded: false,
    items: [
      {
        label: 'Daftar Kursus',
        path: '/library'
      }
    ]
  },
  {
    label: 'Sistem Audit',
    icon: 'pi pi-check-square',
    expanded: true,
    items: [
      {
        label: 'Manajemen Outlet',
        path: '/outlets'
      },
      {
        label: 'Kriteria Checklist',
        path: '/checklist-builder'
      },
      {
        label: 'Laporan Inspeksi',
        path: '/audit-reports'
      }
    ]
  },
  {
    label: 'Analytics & Report',
    icon: 'pi pi-chart-pie',
    expanded: true,
    items: [
      {
        label: 'Gamifikasi & Kuis',
        icon: 'pi pi-star',
        expanded: true,
        items: [
          { label: 'Papan Peringkat (XP)', path: '/analytics/leaderboard' },
          { label: 'Riwayat Kuis', path: '/analytics/quiz-history' }
        ]
      },
      {
        label: 'Training & Development',
        icon: 'pi pi-chart-line',
        expanded: true,
        items: [
          { label: 'In Class Training', path: '/analytics/training/in-class' },
          { label: 'On Site Training', path: '/analytics/training/on-site' },
          { label: 'Online Training (Quiz)', path: '/analytics/training/online' }
        ]
      },
      {
        label: 'Audit & Assessment',
        icon: 'pi pi-chart-bar',
        path: '/analytics/audit'
      }
    ]
  },
  {
    label: 'Standar Operasional (SOP)',
    icon: 'pi pi-file',
    expanded: false,
    items: [
      {
        label: 'Pustaka SOP',
        path: '/sop/viewer'
      },
      {
        label: 'Unggah SOP (Admin)',
        path: '/sop/management'
      }
    ]
  },
  {
    label: 'Pustaka Materi',
    icon: 'pi pi-folder-open',
    path: '/library'
  },
  {
    label: 'Manajemen Karyawan',
    icon: 'pi pi-users',
    path: '/employees'
  }
]);

const navigate = (item: any) => {
  if (item.items) {
    item.expanded = !item.expanded;
  } else if (item.path) {
    router.push(item.path);
  }
};

const isActive = (path: string) => {
  return route.path === path;
};
</script>

<template>
  <aside class="w-72 bg-white border-r border-gray-200 flex flex-col hidden md:flex h-screen sticky top-0 shrink-0 shadow-sm">
    <!-- Header -->
    <div class="p-5 border-b border-gray-100 flex items-center gap-3">
      <div class="w-9 h-9 bg-primary/10 rounded-xl flex items-center justify-center">
        <i class="pi pi-building text-primary text-lg"></i>
      </div>
      <div>
        <h1 class="font-bold text-lg text-primary tracking-tight leading-tight">TND SYSTEM</h1>
        <p class="text-[11px] text-gray-500 font-medium">Learning Management System</p>
      </div>
    </div>
    
    <!-- Menu -->
    <div class="flex-1 overflow-y-auto custom-scrollbar px-3 py-4 space-y-1">
      <template v-for="(item, index) in menu" :key="index">
        
        <!-- Parent Menu Item -->
        <div 
          @click="navigate(item)" 
          class="flex items-center px-3 py-2.5 rounded-lg cursor-pointer transition-all duration-200 group select-none"
          :class="[
            isActive(item.path) ? 'bg-primary/10 text-primary font-bold' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900',
            item.expanded ? 'bg-gray-50/50' : ''
          ]"
        >
          <i :class="[item.icon, 'text-lg mr-3 w-5 text-center', isActive(item.path) ? 'text-primary' : 'text-gray-400 group-hover:text-gray-600']"></i>
          <span class="text-[13px] flex-1 font-medium whitespace-nowrap">{{ item.label }}</span>
          <i v-if="item.items" class="pi text-xs transition-transform duration-200 text-gray-400" :class="item.expanded ? 'pi-chevron-down' : 'pi-chevron-right'"></i>
        </div>

        <!-- Level 1 Submenu -->
        <div v-if="item.items" 
             class="grid transition-all duration-300 ease-in-out" 
             :class="item.expanded ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'">
          <div class="overflow-hidden">
            <div class="pl-4 mt-1 space-y-1 mb-2 border-l-2 border-gray-100 ml-5">
              <template v-for="(subItem, subIndex) in item.items" :key="subIndex">
                
                <div 
                  @click="navigate(subItem)"
                  class="flex items-center px-3 py-2 rounded-lg cursor-pointer transition-all duration-200 group select-none"
                  :class="isActive(subItem.path) ? 'bg-primary/5 text-primary font-bold' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-800'"
                >
                  <i v-if="subItem.icon" :class="[subItem.icon, 'text-sm mr-2.5 w-4 text-center', isActive(subItem.path) ? 'text-primary' : 'text-gray-400 group-hover:text-gray-600']"></i>
                  <span class="text-[13px] flex-1 font-medium whitespace-nowrap">{{ subItem.label }}</span>
                  <i v-if="subItem.items" class="pi text-[10px] transition-transform duration-200 text-gray-400" :class="subItem.expanded ? 'pi-chevron-down' : 'pi-chevron-right'"></i>
                </div>

                <!-- Level 2 Submenu -->
                <div v-if="subItem.items" 
                     class="grid transition-all duration-300 ease-in-out" 
                     :class="subItem.expanded ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'">
                  <div class="overflow-hidden">
                    <div class="pl-3 mt-1 space-y-1 mb-1 border-l-2 border-gray-100 ml-4">
                      <div 
                        v-for="(subSubItem, subSubIndex) in subItem.items" 
                        :key="subSubIndex"
                        @click="navigate(subSubItem)"
                        class="flex items-center px-3 py-2 rounded-lg cursor-pointer transition-all duration-200 select-none"
                        :class="isActive(subSubItem.path) ? 'text-primary font-bold bg-primary/5' : 'text-gray-500 hover:text-gray-800 hover:bg-gray-50'"
                      >
                        <span class="text-xs font-medium whitespace-nowrap">{{ subSubItem.label }}</span>
                      </div>
                    </div>
                  </div>
                </div>

              </template>
            </div>
          </div>
        </div>
      </template>
    </div>
    
    <!-- User Profile -->
    <div class="p-4 border-t border-gray-100 bg-gray-50/30">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 rounded-full bg-secondary text-white flex items-center justify-center font-bold shadow-sm">
          B
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-[13px] font-bold text-gray-800 truncate">Halo, Budi!</p>
          <p class="text-[11px] text-gray-500 truncate">Instruktur Utama</p>
        </div>
      </div>
    </div>
  </aside>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar {
  width: 4px;
}
.custom-scrollbar::-webkit-scrollbar-track {
  background: transparent;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background: #e2e8f0;
  border-radius: 4px;
}
.custom-scrollbar:hover::-webkit-scrollbar-thumb {
  background: #cbd5e1;
}
</style>
