// frontend/src/views/EmployeeManagement.tsx
import React from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Users, RefreshCw, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageHeader } from '@/components/common/PageHeader';
import { DataTable, ColumnDef } from '@/components/common/DataTable';
import { getApiUrl } from '@/lib/api';

interface Employee {
  id: string;
  hris_user_id: string;
  full_name: string;
  email: string;
  join_date?: string;
}

export const EmployeeManagement: React.FC = () => {
  const queryClient = useQueryClient();

  const { data: employees = [], isLoading } = useQuery<Employee[]>({
    queryKey: ['employees'],
    queryFn: async () => {
      const res = await fetch(getApiUrl('/sync/employees'));
      if (!res.ok) throw new Error('Failed to fetch employees');
      return res.json();
    },
  });

  const syncMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(getApiUrl('/sync/employees/sync-hris'), {
        method: 'POST',
      });
      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Gagal sinkronisasi Karyawan HRIS.');
      }
      return data;
    },
    onSuccess: (data) => {
      alert(data.message || 'Sinkronisasi berhasil!');
      queryClient.invalidateQueries({ queryKey: ['employees'] });
    },
    onError: (err: any) => {
      alert(err.message || 'Tidak dapat terhubung ke Backend NestJS atau Server HRIS.');
    },
  });

  const columns: ColumnDef<Employee>[] = [
    {
      key: 'hris_user_id',
      header: 'ID (HRIS)',
      sortable: true,
      render: (row) => (
        <span className="font-mono text-xs text-slate-500 font-semibold">
          {row.hris_user_id}
        </span>
      ),
    },
    {
      key: 'full_name',
      header: 'Nama Karyawan',
      sortable: true,
      render: (row) => <span className="font-bold text-slate-800">{row.full_name}</span>,
    },
    {
      key: 'email',
      header: 'Email',
      render: (row) => <span className="text-slate-600">{row.email || '-'}</span>,
    },
    {
      key: 'join_date',
      header: 'Tanggal Bergabung',
      sortable: true,
      render: (row) => (
        <span className="text-slate-500 text-xs">
          {row.join_date
            ? new Date(row.join_date).toLocaleDateString('id-ID', {
                day: 'numeric',
                month: 'long',
                year: 'numeric',
              })
            : '-'}
        </span>
      ),
    },
  ];

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-6">
      {/* Reusable Page Header */}
      <PageHeader
        title="Manajemen Karyawan"
        subtitle="Kelola data karyawan yang disinkronisasi otomatis dari HRIS"
        icon={<Users className="w-7 h-7" />}
        actions={
          <Button
            onClick={() => syncMutation.mutate()}
            disabled={syncMutation.isPending}
            className="bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold flex items-center gap-2 shadow-sm"
          >
            {syncMutation.isPending ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <RefreshCw className="w-4 h-4" />
            )}
            Sync Karyawan dari HRIS
          </Button>
        }
      />

      {/* Reusable Data Table */}
      <DataTable
        data={employees}
        columns={columns}
        isLoading={isLoading}
        searchPlaceholder="Cari ID, nama, atau email karyawan..."
        emptyMessage="Belum ada data karyawan. Klik 'Sync Karyawan dari HRIS' untuk menarik data."
      />
    </div>
  );
};

// lms-frontend/src/views/EmployeeManagement.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import Button from 'primevue/button';
import AppSidebar from '@/components/layout/AppSidebar.vue';

const employees = ref([]);
const loading = ref(false);
const syncing = ref(false);

const fetchEmployees = async () => {
  loading.value = true;
  try {
    const res = await fetch('http://localhost:3001/sync/employees');
    if (res.ok) {
      employees.value = await res.json();
    }
  } catch (error) {
    console.error('Error fetching employees:', error);
  } finally {
    loading.value = false;
  }
};

const syncHRIS = async () => {
  syncing.value = true;
  try {
    const res = await fetch('http://localhost:3001/sync/employees/sync-hris', { method: 'POST' });
    const data = await res.json();
    if (res.ok && data.success) {
      alert(data.message);
      await fetchEmployees();
    } else {
      alert(data.message || 'Gagal sinkronisasi Karyawan HRIS.');
    }
  } catch (error) {
    console.error('Error syncing:', error);
    alert('Tidak dapat terhubung ke Backend NestJS atau Backend gagal menghubungi Server HRIS (Pastikan Server HRIS berjalan).');
  } finally {
    syncing.value = false;
  }
};

onMounted(() => {
  fetchEmployees();
});
</script>

<template>
  <div class="flex h-screen bg-gray-50 overflow-hidden font-sans text-sm">
    <AppSidebar />
    <main class="flex-1 overflow-y-auto">
      <div class="p-6 md:p-8 max-w-7xl mx-auto space-y-6">
        <!-- Header -->
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 class="text-2xl font-bold text-gray-800">Manajemen Karyawan</h1>
            <p class="text-gray-500 mt-1">Kelola data karyawan yang disinkronisasi otomatis dari HRIS</p>
          </div>
          <div class="flex gap-2">
            <Button 
              @click="syncHRIS" 
              :loading="syncing" 
              icon="pi pi-sync" 
              label="Sync Karyawan dari HRIS" 
              severity="info" 
            />
          </div>
        </div>

        <!-- Data Table -->
        <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          <DataTable :value="employees" :loading="loading" paginator :rows="10" 
                     dataKey="id" class="p-datatable-sm" 
                     emptyMessage="Belum ada data karyawan. Klik 'Sync Karyawan dari HRIS' untuk menarik data.">
            
            <Column field="hris_user_id" header="ID (HRIS)" sortable></Column>
            <Column field="full_name" header="Nama Karyawan" sortable></Column>
            <Column field="email" header="Email"></Column>
            <Column field="join_date" header="Tanggal Bergabung" sortable>
              <template #body="{ data }">
                {{ data.join_date ? new Date(data.join_date).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }) : '-' }}
              </template>
            </Column>
          </DataTable>
        </div>
      </div>
    </main>
  </div>
</template>

<style scoped>
:deep(.p-datatable .p-datatable-thead > tr > th) {
  background-color: #f8fafc;
  color: #475569;
  font-weight: 700;
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  padding: 1rem;
}
:deep(.p-datatable .p-datatable-tbody > tr > td) {
  padding: 1rem;
  border-bottom: 1px solid #f1f5f9;
}
</style>
