// frontend/src/views/LibraryView.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import {
  FolderOpen,
  Search,
  CloudDownload,
  Plus,
  Zap,
  Eye,
  Pencil,
  FileText,
  HelpCircle,
  Star,
  Loader2,
  FileCheck,
  Check,
  X,
  Upload,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { PageHeader } from '@/components/common/PageHeader';
import { EmptyState } from '@/components/common/EmptyState';
import { StatusBadge } from '@/components/common/StatusBadge';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { getApiUrl } from '@/lib/api';

interface Material {
  id: string;
  type: string;
  content_url: string;
  Quiz?: any;
}

interface Course {
  id: string;
  title: string;
  description: string;
  thumbnail_url: string;
  reward_points: number;
  Materials?: Material[];
}

interface QuizItem {
  id: string;
  passing_score: number;
  Material?: {
    Course?: {
      title: string;
    };
  };
  _count?: {
    Questions: number;
    EmployeeQuizAttempts: number;
  };
}

export const LibraryView: React.FC = () => {
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [activeTab, setActiveTab] = useState<'materi' | 'kuis'>('materi');
  const [searchQuery, setSearchQuery] = useState('');
  const [showDialog, setShowDialog] = useState(false);
  const [isEdit, setIsEdit] = useState(false);
  const [currentId, setCurrentId] = useState('');
  const [isUploading, setIsUploading] = useState(false);
  const [syncing, setSyncing] = useState(false);

  const [formData, setFormData] = useState({
    title: '',
    description: '',
    type: 'PDF',
    thumbnail_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=400&q=80',
    reward_points: 100,
  });
  const [uploadedFileUrl, setUploadedFileUrl] = useState('');

  // Fetch Courses
  const { data: courses = [], isLoading: isLoadingCourses } = useQuery<Course[]>({
    queryKey: ['courses'],
    queryFn: async () => {
      const res = await fetch(getApiUrl('/lms/courses'));
      if (!res.ok) throw new Error('Failed to load courses');
      return res.json();
    },
  });

  // Fetch Quizzes
  const { data: quizzes = [], isLoading: isLoadingQuizzes } = useQuery<QuizItem[]>({
    queryKey: ['quizzes'],
    queryFn: async () => {
      const res = await fetch(getApiUrl('/quizzes/all'));
      if (!res.ok) throw new Error('Failed to load quizzes');
      return res.json();
    },
    enabled: activeTab === 'kuis',
  });

  const openCreateModal = () => {
    setIsEdit(false);
    setCurrentId('');
    setFormData({
      title: '',
      description: '',
      type: 'PDF',
      thumbnail_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=400&q=80',
      reward_points: 100,
    });
    setUploadedFileUrl('');
    setShowDialog(true);
  };

  const openEditModal = (item: Course) => {
    setIsEdit(true);
    setCurrentId(item.id);
    setFormData({
      title: item.title,
      description: item.description,
      type: item.Materials?.[0]?.type || 'PDF',
      thumbnail_url: item.thumbnail_url || '',
      reward_points: item.reward_points || 0,
    });
    setUploadedFileUrl(item.Materials?.[0]?.content_url || '');
    setShowDialog(true);
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    const body = new FormData();
    body.append('file', file);

    try {
      const res = await fetch(getApiUrl('/lms/courses/upload'), {
        method: 'POST',
        body,
      });
      const data = await res.json();
      if (res.ok && data.success) {
        setUploadedFileUrl(data.url);
        alert('File berhasil diunggah!');
      } else {
        alert(data.message || 'Gagal mengunggah file.');
      }
    } catch (err) {
      console.error(err);
      alert('Terjadi kesalahan saat upload.');
    } finally {
      setIsUploading(false);
    }
  };

  const handleSaveCourse = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.title) return alert('Judul wajib diisi');
    if (!isEdit && !uploadedFileUrl) {
      return alert('Silakan pilih dan unggah file materi (PDF/Video) terlebih dahulu!');
    }

    const payload = {
      title: formData.title,
      description: formData.description,
      thumbnail_url: formData.thumbnail_url,
      reward_points: Number(formData.reward_points),
      materials: uploadedFileUrl
        ? [{ type: formData.type, content_url: uploadedFileUrl, min_read_time: 0 }]
        : undefined,
    };

    try {
      const url = isEdit
        ? getApiUrl(`/lms/courses/${currentId}`)
        : getApiUrl('/lms/courses');
      const method = isEdit ? 'PATCH' : 'POST';

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      if (res.ok) {
        alert(isEdit ? 'Berhasil diperbarui' : 'Berhasil ditambahkan');
        setShowDialog(false);
        queryClient.invalidateQueries({ queryKey: ['courses'] });
      } else {
        alert('Gagal menyimpan materi');
      }
    } catch (err) {
      console.error(err);
      alert('Terjadi kesalahan saat menyimpan');
    }
  };

  const handleSyncHRIS = () => {
    setSyncing(true);
    setTimeout(() => {
      setSyncing(false);
      alert('Sinkronisasi HRIS selesai. (Mobile app HRIS dapat mengambil data terbaru)');
    }, 1000);
  };

  const filteredCourses = courses.filter((c) =>
    c.title?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    c.description?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-6">
      {/* Reusable Page Header */}
      <PageHeader
        title="Pustaka Materi"
        subtitle="Kelola modul PDF, Video, dan Kuis. Tersinkronisasi dengan HRIS."
        icon={<FolderOpen className="w-7 h-7" />}
        actions={
          <>
            <div className="relative w-full sm:w-64">
              <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
              <Input
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Cari materi..."
                className="pl-9 h-10 rounded-xl bg-slate-50 border-slate-200 text-sm"
              />
            </div>
            <Button
              variant="outline"
              onClick={handleSyncHRIS}
              disabled={syncing}
              className="font-semibold flex items-center gap-2 border-slate-200"
            >
              {syncing ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <CloudDownload className="w-4 h-4 text-[#419CC3]" />
              )}
              Sync HRIS
            </Button>
            <Button
              onClick={openCreateModal}
              className="bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold flex items-center gap-2 shadow-sm"
            >
              <Plus className="w-4 h-4" /> Buat Baru
            </Button>
          </>
        }
      />

      {/* Tabs */}
      <div className="flex gap-6 border-b border-slate-200">
        <button
          onClick={() => setActiveTab('materi')}
          className={`pb-3 font-bold text-sm transition-colors border-b-2 flex items-center gap-2 ${
            activeTab === 'materi'
              ? 'border-[#419CC3] text-[#419CC3]'
              : 'border-transparent text-slate-500 hover:text-slate-700'
          }`}
        >
          <FileText className="w-4 h-4" /> Pustaka Materi
        </button>
        <button
          onClick={() => setActiveTab('kuis')}
          className={`pb-3 font-bold text-sm transition-colors border-b-2 flex items-center gap-2 ${
            activeTab === 'kuis'
              ? 'border-[#419CC3] text-[#419CC3]'
              : 'border-transparent text-slate-500 hover:text-slate-700'
          }`}
        >
          <HelpCircle className="w-4 h-4" /> Manajemen Kuis
        </button>
      </div>

      {/* MATERI TAB */}
      {activeTab === 'materi' && (
        <>
          {isLoadingCourses ? (
            <div className="text-center py-16">
              <Loader2 className="w-8 h-8 animate-spin mx-auto text-[#419CC3] mb-3" />
              <p className="text-sm text-slate-500">Memuat materi pelatihan...</p>
            </div>
          ) : filteredCourses.length === 0 ? (
            <EmptyState
              icon={<FolderOpen className="w-8 h-8" />}
              title="Belum ada materi"
              description="Klik tombol 'Buat Baru' untuk mengunggah PDF atau Video Pelatihan."
              actionLabel="Unggah Materi Sekarang"
              onAction={openCreateModal}
              actionIcon={<Plus className="w-4 h-4" />}
            />
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredCourses.map((item) => {
                const materialType = item.Materials?.[0]?.type || 'PDF';
                const hasQuiz = Boolean(item.Materials?.[0]?.Quiz);

                return (
                  <div
                    key={item.id}
                    className="bg-white rounded-2xl border border-slate-200 shadow-sm hover:shadow-xl transition-all duration-300 overflow-hidden flex flex-col group hover:-translate-y-1"
                  >
                    {/* Card Thumbnail */}
                    <div className="h-44 overflow-hidden relative bg-slate-100">
                      <img
                        src={item.thumbnail_url}
                        alt={item.title}
                        className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                      />
                      <div className="absolute top-3 right-3 z-10">
                        <Badge variant="secondary" className="bg-white/90 backdrop-blur-md text-slate-800 font-bold shadow-xs">
                          {materialType}
                        </Badge>
                      </div>
                    </div>

                    {/* Card Body */}
                    <div className="p-5 flex-1 flex flex-col justify-between">
                      <div>
                        <h3 className="font-bold text-base text-slate-800 line-clamp-1 group-hover:text-[#419CC3] transition-colors">
                          {item.title}
                        </h3>
                        <p className="text-xs text-slate-500 mt-1 line-clamp-2 leading-relaxed">
                          {item.description || 'Tidak ada deskripsi.'}
                        </p>
                      </div>

                      <div className="mt-4 pt-4 border-t border-slate-100 flex items-center justify-between">
                        <span className="text-xs font-bold text-slate-600 flex items-center gap-1">
                          <Star className="w-3.5 h-3.5 text-amber-500 fill-amber-500" />
                          {item.reward_points} Poin
                        </span>
                        <StatusBadge
                          status={item.Materials?.length ? 'published' : 'draft'}
                        />
                      </div>

                      {/* Card Actions */}
                      <div className="mt-4 space-y-2">
                        {!hasQuiz && (
                          <Button
                            size="sm"
                            variant="secondary"
                            onClick={() => navigate(`/library/generate-quiz?courseId=${item.id}`)}
                            className="w-full bg-[#419CC3]/10 hover:bg-[#419CC3]/20 text-[#419CC3] font-bold text-xs flex items-center justify-center gap-1.5"
                          >
                            <Zap className="w-3.5 h-3.5" /> Generate Kuis Cepat
                          </Button>
                        )}
                        <div className="flex gap-2">
                          <Button
                            size="sm"
                            onClick={() => navigate(`/library/course/${item.id}`)}
                            className="flex-1 bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold text-xs flex items-center justify-center gap-1.5"
                          >
                            <Eye className="w-3.5 h-3.5" /> Detail
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => openEditModal(item)}
                            className="flex-1 font-bold text-xs flex items-center justify-center gap-1.5 border-slate-200"
                          >
                            <Pencil className="w-3.5 h-3.5" /> Edit
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </>
      )}

      {/* KUIS TAB */}
      {activeTab === 'kuis' && (
        <>
          {isLoadingQuizzes ? (
            <div className="text-center py-16">
              <Loader2 className="w-8 h-8 animate-spin mx-auto text-[#419CC3] mb-3" />
              <p className="text-sm text-slate-500">Memuat daftar kuis...</p>
            </div>
          ) : quizzes.length === 0 ? (
            <EmptyState
              icon={<HelpCircle className="w-8 h-8" />}
              title="Belum ada Kuis"
              description="Belum ada modul kuis evaluasi yang dibuat."
            />
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {quizzes.map((q) => (
                <div
                  key={q.id}
                  className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm flex flex-col justify-between"
                >
                  <div>
                    <h3 className="font-bold text-base text-slate-800 line-clamp-2">
                      Kuis: {q.Material?.Course?.title || 'Umum'}
                    </h3>
                    <p className="text-xs text-slate-500 mt-1">
                      Nilai Kelulusan:{' '}
                      <strong className="text-[#419CC3]">{q.passing_score}</strong>
                    </p>

                    <div className="grid grid-cols-2 gap-3 mt-4">
                      <div className="text-center p-3 bg-slate-50 rounded-xl">
                        <p className="text-lg font-extrabold text-slate-800">
                          {q._count?.Questions || 0}
                        </p>
                        <p className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">
                          Soal
                        </p>
                      </div>
                      <div className="text-center p-3 bg-slate-50 rounded-xl">
                        <p className="text-lg font-extrabold text-slate-800">
                          {q._count?.EmployeeQuizAttempts || 0}
                        </p>
                        <p className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">
                          Peserta
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className="mt-6 pt-4 border-t border-slate-100">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => navigate('/quiz-builder')}
                      className="w-full font-bold text-xs flex items-center justify-center gap-2 border-slate-200"
                    >
                      <Pencil className="w-3.5 h-3.5" /> Edit Soal
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </>
      )}

      {/* Create / Edit Dialog */}
      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="max-w-md rounded-2xl p-6">
          <DialogHeader>
            <DialogTitle className="text-lg font-bold text-slate-800">
              {isEdit ? 'Edit Materi Pelatihan' : 'Buat Materi Baru'}
            </DialogTitle>
          </DialogHeader>

          <form onSubmit={handleSaveCourse} className="space-y-4 pt-2">
            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 uppercase">Judul Course</label>
              <Input
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                placeholder="Contoh: Orientasi Kasir"
                required
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 uppercase">Deskripsi</label>
              <Textarea
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                rows={2}
                placeholder="Deskripsi modul materi..."
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <label className="text-xs font-bold text-slate-700 uppercase">Tipe File</label>
                <Input
                  value={formData.type}
                  onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                  placeholder="PDF / VIDEO"
                />
              </div>
              <div className="space-y-1">
                <label className="text-xs font-bold text-slate-700 uppercase">Poin Reward</label>
                <Input
                  type="number"
                  value={formData.reward_points}
                  onChange={(e) => setFormData({ ...formData, reward_points: Number(e.target.value) })}
                />
              </div>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 uppercase">
                Unggah File Materi (PDF / MP4)
              </label>
              <div className="border-2 border-dashed border-slate-200 rounded-xl p-4 text-center hover:bg-slate-50 transition-colors">
                <input
                  type="file"
                  id="course-file"
                  accept="application/pdf,video/*"
                  onChange={handleFileUpload}
                  className="hidden"
                />
                <label
                  htmlFor="course-file"
                  className="cursor-pointer flex flex-col items-center justify-center gap-1"
                >
                  {isUploading ? (
                    <Loader2 className="w-6 h-6 text-[#419CC3] animate-spin" />
                  ) : (
                    <Upload className="w-6 h-6 text-slate-400" />
                  )}
                  <span className="text-xs font-bold text-[#419CC3]">
                    {isUploading ? 'Sedang Mengunggah...' : 'Pilih File PDF / Video'}
                  </span>
                </label>
              </div>
              {uploadedFileUrl && (
                <div className="text-xs text-[#419CC3] font-bold mt-2 flex items-center gap-1.5 bg-[#419CC3]/10 p-2.5 rounded-lg">
                  <FileCheck className="w-4 h-4" /> Terlampir: {uploadedFileUrl.split('/').pop()}
                </div>
              )}
            </div>

            <DialogFooter className="gap-2 pt-4 border-t border-slate-100">
              <Button type="button" variant="ghost" onClick={() => setShowDialog(false)}>
                <X className="w-4 h-4 mr-1" /> Batal
              </Button>
              <Button type="submit" className="bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold">
                <Check className="w-4 h-4 mr-1" /> Simpan
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
};

// lms-frontend/src/views/LibraryView.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import AppSidebar from '@/components/layout/AppSidebar.vue';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Tag from 'primevue/tag';
import Card from 'primevue/card';
import Dialog from 'primevue/dialog';
import Textarea from 'primevue/textarea';
import FileUpload from 'primevue/fileupload';

const router = useRouter();

const materials = ref([]);
const quizzes = ref([]);
const activeTab = ref('materi');
const searchQuery = ref('');
const syncing = ref(false);
const loading = ref(false);

const showDialog = ref(false);
const isEdit = ref(false);
const currentId = ref('');
const formData = ref({
  title: '',
  description: '',
  type: 'PDF',
  thumbnail_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=400&q=80',
  reward_points: 0,
});
const uploadedFileUrl = ref('');

const fetchMaterials = async () => {
  loading.value = true;
  try {
    const res = await fetch('http://localhost:3001/lms/courses');
    if (res.ok) {
      materials.value = await res.json();
    }
  } catch (error) {
    console.error(error);
  } finally {
    loading.value = false;
  }
};

const fetchQuizzes = async () => {
  loading.value = true;
  try {
    const res = await fetch('http://localhost:3001/api/gamification/all'); // wait, the route is /quizzes/all not gamification
    // let me fix the URL
    const resQuiz = await fetch('http://localhost:3001/quizzes/all');
    if (resQuiz.ok) {
      quizzes.value = await resQuiz.json();
    }
  } catch (error) {
    console.error(error);
  } finally {
    loading.value = false;
  }
};

const switchTab = (tab: string) => {
  activeTab.value = tab;
  if (tab === 'materi') fetchMaterials();
  if (tab === 'kuis') fetchQuizzes();
};

const openCreateModal = () => {
  isEdit.value = false;
  currentId.value = '';
  formData.value = {
    title: '',
    description: '',
    type: 'PDF',
    thumbnail_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=400&q=80',
    reward_points: 100,
  };
  uploadedFileUrl.value = '';
  showDialog.value = true;
};

const openEditModal = (item: any) => {
  isEdit.value = true;
  currentId.value = item.id;
  formData.value = {
    title: item.title,
    description: item.description,
    type: item.Materials?.[0]?.type || 'PDF',
    thumbnail_url: item.thumbnail_url,
    reward_points: item.reward_points || 0,
  };
  uploadedFileUrl.value = item.Materials?.[0]?.content_url || '';
  showDialog.value = true;
};

const onUpload = async (event: any) => {
  const res = JSON.parse(event.xhr.response);
  if (res && res.success) {
    uploadedFileUrl.value = res.url;
    alert('File berhasil diunggah!');
  }
};

const saveMaterial = async () => {
  if (!formData.value.title) return alert('Judul wajib diisi');
  if (!isEdit.value && !uploadedFileUrl.value) return alert('Silakan pilih dan unggah file materi (PDF/Video) terlebih dahulu!');

  const payload = {
    title: formData.value.title,
    description: formData.value.description,
    thumbnail_url: formData.value.thumbnail_url,
    reward_points: Number(formData.value.reward_points),
    materials: uploadedFileUrl.value ? [
      { type: formData.value.type, content_url: uploadedFileUrl.value, min_read_time: 0 }
    ] : undefined
  };

  try {
    const url = isEdit.value 
      ? `http://localhost:3001/lms/courses/${currentId.value}`
      : 'http://localhost:3001/lms/courses';
      
    const method = isEdit.value ? 'PATCH' : 'POST';

    const res = await fetch(url, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    if (res.ok) {
      alert(isEdit.value ? 'Berhasil diperbarui' : 'Berhasil ditambahkan');
      showDialog.value = false;
      fetchMaterials();
    }
  } catch (error) {
    console.error(error);
    alert('Terjadi kesalahan saat menyimpan');
  }
};

const syncMaterials = async () => {
  syncing.value = true;
  setTimeout(() => {
    syncing.value = false;
    alert('Sinkronisasi HRIS selesai. (Mobile app HRIS dapat mengambil data terbaru dari backend LMS ini)');
  }, 1000);
};

onMounted(() => {
  fetchMaterials();
});
</script>

<template>
  <div class="flex h-screen bg-gray-50 overflow-hidden font-sans text-sm">
    <AppSidebar />
    <main class="flex-1 overflow-y-auto">
      <div class="p-6 md:p-8 max-w-7xl mx-auto space-y-6">
        
        <!-- Header Section -->
        <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white/70 backdrop-blur-xl p-6 rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-white/50 relative overflow-hidden">
          <div class="absolute inset-0 bg-gradient-to-r from-[#419CC3]/5 to-transparent pointer-events-none"></div>
          <div class="relative z-10">
            <h1 class="text-3xl font-extrabold text-slate-800 tracking-tight flex items-center gap-3">
              Pustaka Materi
            </h1>
            <p class="text-slate-500 mt-1 font-medium">Kelola modul PDF, Video, dan Kuis. Tersinkronisasi dengan HRIS.</p>
          </div>
          <div class="flex flex-wrap items-center gap-3 w-full md:w-auto">
            <span class="p-input-icon-left flex-1 md:flex-none">
              <i class="pi pi-search" />
              <InputText v-model="searchQuery" placeholder="Cari materi..." class="w-full md:w-64" />
            </span>
            <Button @click="syncMaterials" :loading="syncing" icon="pi pi-cloud-download" label="Sync HRIS" severity="info" />
            <Button @click="openCreateModal" icon="pi pi-plus" label="Buat Baru" severity="primary" />
          </div>
        </div>

        <!-- Tabs Navigation -->
        <div class="flex gap-4 border-b border-gray-200">
          <button @click="switchTab('materi')" 
            :class="activeTab === 'materi' ? 'border-primary text-primary font-bold' : 'border-transparent text-gray-500 hover:text-gray-700'"
            class="pb-3 border-b-2 transition-colors px-1 text-base">
            Pustaka Materi
          </button>
          <button @click="switchTab('kuis')" 
            :class="activeTab === 'kuis' ? 'border-primary text-primary font-bold' : 'border-transparent text-gray-500 hover:text-gray-700'"
            class="pb-3 border-b-2 transition-colors px-1 text-base flex items-center gap-2">
            Manajemen Kuis
          </button>
        </div>

        <div v-if="loading" class="text-center py-10"><i class="pi pi-spin pi-spinner text-3xl text-primary"></i></div>
        
        <!-- MATERI TAB -->
        <div v-else-if="activeTab === 'materi'">
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
          <Card v-for="item in materials" :key="item.id" class="overflow-hidden border-none shadow-[0_8px_30px_rgb(0,0,0,0.06)] hover:shadow-[0_20px_40px_rgb(65,156,195,0.15)] transition-all duration-500 rounded-2xl bg-white group hover:-translate-y-1">
            <template #header>
              <div class="h-48 overflow-hidden relative">
                <div class="absolute inset-0 bg-gradient-to-t from-slate-900/60 via-slate-900/10 to-transparent z-10 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                <img :src="item.thumbnail_url" :alt="item.title" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" />
                <div class="absolute top-4 right-4 z-20">
                  <Tag :value="item.Materials?.[0]?.type || 'N/A'" severity="secondary" class="shadow-lg font-bold bg-white/90 text-slate-800 backdrop-blur-md px-3 py-1 rounded-full" />
                </div>
              </div>
            </template>
            <template #title>
              <div class="text-xl font-bold text-slate-800 line-clamp-1 group-hover:text-[#419CC3] transition-colors" :title="item.title">
                {{ item.title }}
              </div>
            </template>
            <template #subtitle>
              <div class="flex items-center gap-2 mt-2">
                <span class="text-xs font-bold text-[#419CC3] bg-[#419CC3]/10 px-3 py-1 rounded-full">{{ item.description || 'Umum' }}</span>
              </div>
            </template>
            <template #content>
              <div class="flex justify-between items-center mt-3 border-t border-slate-100 pt-4">
                <span class="text-xs text-slate-500 font-bold flex items-center gap-1"><i class="pi pi-star-fill text-yellow-400"></i> {{ item.reward_points }} Poin</span>
                <Tag v-if="item.Materials?.length" value="published" severity="info" class="rounded-full px-3" />
                <Tag v-else value="draft" severity="warning" class="rounded-full px-3" />
              </div>
            </template>
            <template #footer>
              <div class="flex flex-col gap-3 mt-2">
                <Button v-if="!item.Materials?.[0]?.Quiz" @click="router.push(`/library/generate-quiz?courseId=${item.id}`)" icon="pi pi-bolt" label="Generate Kuis Cepat" severity="info" class="w-full text-sm font-bold shadow-md shadow-[#419CC3]/20" />
                <div class="flex gap-2">
                  <Button @click="router.push(`/library/course/${item.id}`)" icon="pi pi-eye" label="Lihat Detail" severity="primary" class="flex-1 font-bold shadow-md shadow-[#419CC3]/20" />
                  <Button @click="openEditModal(item)" icon="pi pi-pencil" label="Edit" severity="secondary" class="flex-1 font-bold" outlined />
                </div>
              </div>
            </template>
          </Card>
        </div>

          <div v-if="materials.length === 0 && !loading" class="bg-white rounded-xl shadow-sm border border-gray-200 p-12 flex flex-col items-center justify-center text-center">
            <div class="w-16 h-16 bg-gray-50 rounded-full flex items-center justify-center mb-4">
              <i class="pi pi-folder-open text-3xl text-gray-400"></i>
            </div>
            <h3 class="text-lg font-bold text-gray-800">Belum ada materi</h3>
            <p class="text-gray-500 max-w-md mx-auto mt-2">Klik tombol "Buat Baru" untuk mengunggah PDF/Video Pelatihan.</p>
          </div>
        </div>

        <!-- KUIS TAB -->
        <div v-else-if="activeTab === 'kuis'">
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            <Card v-for="q in quizzes" :key="q.id" class="border-none shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-2xl bg-white">
              <template #title>
                <div class="text-xl font-bold text-slate-800 line-clamp-2">
                  Kuis: {{ q.Material?.Course?.title || 'Unknown' }}
                </div>
              </template>
              <template #subtitle>
                <span class="text-sm font-medium text-slate-500">Nilai Kelulusan: <strong class="text-primary">{{ q.passing_score }}</strong></span>
              </template>
              <template #content>
                <div class="flex gap-4 mt-2">
                  <div class="text-center p-3 bg-gray-50 rounded-lg flex-1">
                    <p class="text-xl font-bold text-slate-800">{{ q._count?.Questions || 0 }}</p>
                    <p class="text-[10px] text-gray-500 uppercase font-bold tracking-wider">Soal</p>
                  </div>
                  <div class="text-center p-3 bg-gray-50 rounded-lg flex-1">
                    <p class="text-xl font-bold text-slate-800">{{ q._count?.EmployeeQuizAttempts || 0 }}</p>
                    <p class="text-[10px] text-gray-500 uppercase font-bold tracking-wider">Peserta</p>
                  </div>
                </div>
              </template>
              <template #footer>
                <div class="flex gap-2 mt-4">
                  <Button icon="pi pi-pencil" label="Edit Soal" severity="secondary" class="flex-1 text-sm" outlined />
                </div>
              </template>
            </Card>
          </div>
          
          <div v-if="quizzes.length === 0 && !loading" class="bg-white rounded-xl shadow-sm border border-gray-200 p-12 text-center mt-4">
            <p class="text-gray-500">Belum ada Kuis yang di-generate.</p>
          </div>
        </div>

      </div>
    </main>
  </div>

  <!-- Dialog for Create / Edit -->
  <Dialog v-model:visible="showDialog" :header="isEdit ? 'Edit Materi' : 'Buat Materi Baru'" :modal="true" class="w-full max-w-md">
    <div class="space-y-4 pt-2">
      <div class="flex flex-col gap-1">
        <label class="font-bold text-xs text-gray-700 uppercase">Judul Course</label>
        <InputText v-model="formData.title" placeholder="Contoh: Pengenalan Kasir" />
      </div>
      <div class="flex flex-col gap-1">
        <label class="font-bold text-xs text-gray-700 uppercase">Kategori / Deskripsi</label>
        <Textarea v-model="formData.description" rows="2" placeholder="Deskripsi materi..." />
      </div>
      <div class="flex flex-col gap-1">
        <label class="font-bold text-xs text-gray-700 uppercase">Tipe File</label>
        <InputText v-model="formData.type" placeholder="PDF / VIDEO" />
      </div>
      <div class="flex flex-col gap-1">
        <label class="font-bold text-xs text-gray-700 uppercase">Poin Reward Penyelesaian</label>
        <InputText v-model="formData.reward_points" type="number" />
      </div>
      
      <div class="flex flex-col gap-1">
        <label class="font-bold text-xs text-gray-700 uppercase">Upload File Materi (Opsional)</label>
        <FileUpload 
          mode="basic" 
          name="file" 
          url="http://localhost:3001/lms/courses/upload" 
          accept="application/pdf,video/*" 
          auto
          @upload="onUpload" 
          chooseLabel="Pilih & Unggah File" 
          class="w-full"
        />
        <div v-if="uploadedFileUrl" class="text-xs text-[#419CC3] font-bold mt-1 flex items-center gap-1">
          <i class="pi pi-file-check"></i> File berhasil dipilih dan terlampir: {{ uploadedFileUrl.split('/').pop() }}
        </div>
      </div>
    </div>
    
    <template #footer>
      <Button label="Batal" icon="pi pi-times" @click="showDialog = false" text />
      <Button label="Simpan" icon="pi pi-check" @click="saveMaterial" severity="primary" />
    </template>
  </Dialog>
</template>

<style scoped>
:deep(.p-card-body) {
  padding: 1.25rem;
}
:deep(.p-card-content) {
  padding: 0;
}
</style>
