// lms-frontend/src/components/ui/DynamicInputList.vue
<template>
  <div class="space-y-3">
    <div 
      v-for="(item, index) in modelValue" 
      :key="index"
      class="flex items-center gap-3 p-3 bg-gray-50 rounded-lg border border-gray-200"
    >
      <!-- Correct Answer Indicator (Radio for single choice, Checkbox for multiple) -->
      <button 
        @click="markCorrect(index)"
        type="button"
        class="w-6 h-6 rounded-full border-2 flex items-center justify-center transition-colors"
        :class="item.is_correct ? 'border-primary bg-primary text-white' : 'border-gray-300 bg-white'"
      >
        <span v-if="item.is_correct" class="material-symbols-outlined text-[14px]">check</span>
      </button>

      <!-- Input Field -->
      <input 
        v-model="item.text"
        type="text" 
        class="flex-1 bg-transparent border-none focus:ring-0 p-0 text-sm"
        :placeholder="`Opsi ${String.fromCharCode(65 + index)}`"
      />

      <!-- Remove Button -->
      <button 
        v-if="modelValue.length > 2"
        @click="removeOption(index)"
        type="button"
        class="text-gray-400 hover:text-red-500 transition-colors p-1"
      >
        <span class="material-symbols-outlined text-[20px]">close</span>
      </button>
    </div>

    <button 
      @click="addOption"
      type="button"
      class="text-sm font-medium text-primary hover:text-primary/80 flex items-center gap-1 mt-2"
    >
      <span class="material-symbols-outlined text-[18px]">add</span>
      Tambah Opsi
    </button>
  </div>
</template>

<script setup lang="ts">
import { defineProps, defineEmits } from 'vue'

export interface OptionItem {
  text: string
  is_correct: boolean
}

const props = defineProps<{
  modelValue: OptionItem[]
  type?: 'MULTIPLE_CHOICE' | 'MULTIPLE_ANSWER' | 'TRUE_FALSE'
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: OptionItem[]): void
}>()

const updateValue = (newValue: OptionItem[]) => {
  emit('update:modelValue', newValue)
}

const markCorrect = (index: number) => {
  const newOptions = [...props.modelValue]
  
  if (props.type === 'MULTIPLE_CHOICE' || props.type === 'TRUE_FALSE') {
    // Single answer mode: uncheck others
    newOptions.forEach((opt, i) => {
      opt.is_correct = i === index
    })
  } else {
    // Multiple answer mode: toggle
    newOptions[index].is_correct = !newOptions[index].is_correct
  }
  
  updateValue(newOptions)
}

const removeOption = (index: number) => {
  const newOptions = props.modelValue.filter((_, i) => i !== index)
  updateValue(newOptions)
}

const addOption = () => {
  updateValue([...props.modelValue, { text: '', is_correct: false }])
}
</script>

// frontend/src/components/ui/DynamicInputList.tsx
import React from 'react';
import { Check, X, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export interface OptionItem {
  text: string;
  is_correct: boolean;
}

interface DynamicInputListProps {
  value: OptionItem[];
  onChange: (items: OptionItem[]) => void;
  type?: 'MULTIPLE_CHOICE' | 'MULTIPLE_ANSWER' | 'TRUE_FALSE';
}

export const DynamicInputList: React.FC<DynamicInputListProps> = ({
  value,
  onChange,
  type = 'MULTIPLE_CHOICE',
}) => {
  const markCorrect = (index: number) => {
    const updated = [...value];
    if (type === 'MULTIPLE_CHOICE' || type === 'TRUE_FALSE') {
      updated.forEach((opt, i) => {
        opt.is_correct = i === index;
      });
    } else {
      updated[index].is_correct = !updated[index].is_correct;
    }
    onChange(updated);
  };

  const removeOption = (index: number) => {
    onChange(value.filter((_, i) => i !== index));
  };

  const addOption = () => {
    onChange([...value, { text: '', is_correct: false }]);
  };

  const updateText = (index: number, text: string) => {
    const updated = [...value];
    updated[index].text = text;
    onChange(updated);
  };

  return (
    <div className="space-y-2.5">
      {value.map((item, index) => (
        <div
          key={index}
          className="flex items-center gap-3 p-2.5 bg-slate-50 rounded-xl border border-slate-200"
        >
          {/* Indicator */}
          <button
            type="button"
            onClick={() => markCorrect(index)}
            className={`w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all shrink-0 ${
              item.is_correct
                ? 'border-[#419CC3] bg-[#419CC3] text-white shadow-xs'
                : 'border-slate-300 bg-white hover:border-slate-400'
            }`}
          >
            {item.is_correct && <Check className="w-3.5 h-3.5 stroke-[3]" />}
          </button>

          {/* Input text */}
          <Input
            value={item.text}
            onChange={(e) => updateText(index, e.target.value)}
            placeholder={`Opsi ${String.fromCharCode(65 + index)}`}
            className="flex-1 bg-transparent border-none shadow-none focus-visible:ring-0 text-sm h-8 p-0"
          />

          {/* Remove Button */}
          {value.length > 2 && (
            <button
              type="button"
              onClick={() => removeOption(index)}
              className="text-slate-400 hover:text-rose-500 transition-colors p-1"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>
      ))}

      {type !== 'TRUE_FALSE' && (
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={addOption}
          className="text-xs font-bold text-[#419CC3] hover:text-[#3484a6] hover:bg-[#419CC3]/5 p-0 h-auto flex items-center gap-1 mt-2"
        >
          <Plus className="w-3.5 h-3.5" /> Tambah Opsi
        </Button>
      )}
    </div>
  );
};
