// frontend/src/views/analytics/LeaderboardView.tsx
import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Award, Pencil, AlertCircle, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { PageHeader } from '@/components/common/PageHeader';
import { DataTable, ColumnDef } from '@/components/common/DataTable';
import { StatusBadge } from '@/components/common/StatusBadge';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { getApiUrl } from '@/lib/api';

interface LeaderboardUser {
  hris_user_id: string;
  full_name: string;
  current_rank: string;
  total_xp: number;
  quizzes_completed: number;
}

export const LeaderboardView: React.FC = () => {
  const [showDialog, setShowDialog] = useState(false);
  const [editData, setEditData] = useState({
    hris_user_id: '',
    full_name: '',
    new_xp: 0,
    reason: '',
  });
  const [savingXp, setSavingXp] = useState(false);

  const { data: users = [], isLoading, refetch } = useQuery<LeaderboardUser[]>({
    queryKey: ['leaderboard'],
    queryFn: async () => {
      const res = await fetch(getApiUrl('/api/gamification/leaderboard'));
      if (!res.ok) throw new Error('Failed to load leaderboard');
      return res.json();
    },
  });

  const openEditModal = (user: LeaderboardUser) => {
    setEditData({
      hris_user_id: user.hris_user_id,
      full_name: user.full_name,
      new_xp: user.total_xp,
      reason: '',
    });
    setShowDialog(true);
  };

  const handleSaveXp = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editData.reason) {
      return alert('Alasan perubahan XP wajib diisi untuk Audit Trail.');
    }

    setSavingXp(true);
    try {
      const res = await fetch(getApiUrl('/api/gamification/adjust-xp'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          hris_user_id: editData.hris_user_id,
          new_xp: Number(editData.new_xp),
          reason: editData.reason,
        }),
      });

      if (res.ok) {
        alert('XP berhasil disesuaikan!');
        setShowDialog(false);
        refetch();
      } else {
        alert('Gagal merubah XP');
      }
    } catch (err) {
      console.error(err);
      alert('Terjadi kesalahan saat menyesuaikan XP.');
    } finally {
      setSavingXp(false);
    }
  };

  const columns: ColumnDef<LeaderboardUser>[] = [
    {
      key: 'rank',
      header: 'Peringkat',
      align: 'center',
      className: 'w-20',
      render: (_, index) => (
        <span className="font-bold text-slate-500 text-xs">#{index + 1}</span>
      ),
    },
    {
      key: 'hris_user_id',
      header: 'ID Karyawan',
      sortable: true,
      render: (row) => (
        <span className="font-mono text-xs text-slate-500 font-semibold">{row.hris_user_id}</span>
      ),
    },
    {
      key: 'full_name',
      header: 'Nama Karyawan',
      sortable: true,
      render: (row) => <span className="font-bold text-slate-800">{row.full_name}</span>,
    },
    {
      key: 'current_rank',
      header: 'Pangkat (Rank)',
      sortable: true,
      render: (row) => <StatusBadge status={row.current_rank} />,
    },
    {
      key: 'total_xp',
      header: 'Total XP',
      sortable: true,
      render: (row) => (
        <span className="font-extrabold text-[#419CC3]">{row.total_xp} XP</span>
      ),
    },
    {
      key: 'quizzes_completed',
      header: 'Kuis Selesai',
      sortable: true,
      render: (row) => <span className="font-semibold text-slate-600">{row.quizzes_completed}</span>,
    },
    {
      key: 'actions',
      header: 'Aksi',
      align: 'center',
      className: 'w-20',
      render: (row) => (
        <Button
          variant="ghost"
          size="icon"
          onClick={() => openEditModal(row)}
          className="text-slate-400 hover:text-[#419CC3] hover:bg-[#419CC3]/10 rounded-full h-8 w-8"
        >
          <Pencil className="w-4 h-4" />
        </Button>
      ),
    },
  ];

  return (
    <div className="p-6 md:p-8 max-w-6xl mx-auto space-y-6">
      {/* Reusable Page Header */}
      <PageHeader
        title="Papan Peringkat (Leaderboard)"
        subtitle="Pantau total XP dan Rank Gamifikasi seluruh karyawan."
        icon={<Award className="w-7 h-7 text-amber-500" />}
      />

      {/* Reusable Data Table */}
      <DataTable
        data={users}
        columns={columns}
        isLoading={isLoading}
        searchPlaceholder="Cari ID atau Nama Karyawan..."
        emptyMessage="Belum ada data peringkat karyawan."
      />

      {/* Edit XP Modal */}
      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="max-w-md rounded-2xl p-6">
          <DialogHeader>
            <DialogTitle className="text-lg font-bold text-slate-800">
              Penyesuaian XP Manual
            </DialogTitle>
          </DialogHeader>

          <form onSubmit={handleSaveXp} className="space-y-4 pt-2">
            <div className="bg-blue-50 text-blue-800 p-3 rounded-xl text-xs font-medium flex items-start gap-2 border border-blue-100">
              <AlertCircle className="w-4 h-4 mt-0.5 shrink-0 text-[#419CC3]" />
              <span>
                Pengubahan XP manual akan mencatat Log Audit Trail. Pastikan Anda memiliki alasan yang
                jelas.
              </span>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 uppercase">Karyawan</label>
              <Input value={editData.full_name} disabled className="bg-slate-100 font-bold" />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 uppercase">Total XP Baru</label>
              <Input
                type="number"
                value={editData.new_xp}
                onChange={(e) => setEditData({ ...editData, new_xp: Number(e.target.value) })}
                required
              />
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 uppercase">
                Alasan Perubahan (Audit Trail) <span className="text-rose-500">*</span>
              </label>
              <Textarea
                value={editData.reason}
                onChange={(e) => setEditData({ ...editData, reason: e.target.value })}
                rows={3}
                placeholder="Contoh: Penyesuaian poin kuis..."
                required
              />
            </div>

            <DialogFooter className="gap-2 pt-3 border-t border-slate-100">
              <Button type="button" variant="ghost" onClick={() => setShowDialog(false)}>
                Batal
              </Button>
              <Button
                type="submit"
                disabled={savingXp}
                className="bg-rose-600 hover:bg-rose-700 text-white font-bold"
              >
                {savingXp ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Simpan Perubahan'}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
};

// lms-frontend/src/views/analytics/LeaderboardView.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import AppSidebar from '@/components/layout/AppSidebar.vue';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import InputText from 'primevue/inputtext';
import Button from 'primevue/button';
import Tag from 'primevue/tag';
import Dialog from 'primevue/dialog';
import Textarea from 'primevue/textarea';

const users = ref([]);
const loading = ref(false);
const searchQuery = ref('');

// Edit XP Modal
const showDialog = ref(false);
const editData = ref({
  hris_user_id: '',
  full_name: '',
  new_xp: 0,
  reason: ''
});

const fetchLeaderboard = async () => {
  loading.value = true;
  try {
    const url = new URL('http://localhost:3001/api/gamification/leaderboard');
    if (searchQuery.value) {
      url.searchParams.append('search', searchQuery.value);
    }
    const res = await fetch(url.toString());
    if (res.ok) {
      users.value = await res.json();
    }
  } catch (error) {
    console.error(error);
  } finally {
    loading.value = false;
  }
};

const getRankSeverity = (rank: string) => {
  if (rank === 'Pakar SobatHR') return 'danger';
  if (rank === 'Master Pengetahuan') return 'warning';
  if (rank === 'Karyawan Terampil') return 'info';
  if (rank === 'Pembelajar Aktif') return 'success';
  return 'secondary';
};

const openEditModal = (user: any) => {
  editData.value = {
    hris_user_id: user.hris_user_id,
    full_name: user.full_name,
    new_xp: user.total_xp,
    reason: ''
  };
  showDialog.value = true;
};

const saveXp = async () => {
  if (!editData.value.reason) return alert('Alasan perubahan XP wajib diisi untuk Audit Trail.');
  
  try {
    const res = await fetch('http://localhost:3001/api/gamification/adjust-xp', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        hris_user_id: editData.value.hris_user_id,
        new_xp: Number(editData.value.new_xp),
        reason: editData.value.reason
      })
    });
    
    if (res.ok) {
      alert('XP berhasil diubah!');
      showDialog.value = false;
      fetchLeaderboard();
    } else {
      alert('Gagal merubah XP');
    }
  } catch (err) {
    console.error(err);
    alert('Terjadi kesalahan');
  }
};

let debounceTimer: any;
const onSearch = () => {
  clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => {
    fetchLeaderboard();
  }, 500);
};

onMounted(() => {
  fetchLeaderboard();
});
</script>

<template>
  <div class="flex h-screen bg-gray-50 overflow-hidden font-sans text-sm">
    <AppSidebar />
    <main class="flex-1 overflow-y-auto p-6 md:p-8">
      <div class="max-w-6xl mx-auto space-y-6">
        
        <div class="flex justify-between items-center bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
          <div>
            <h1 class="text-2xl font-extrabold text-slate-800 tracking-tight">Papan Peringkat (Leaderboard)</h1>
            <p class="text-slate-500 mt-1">Pantau total XP dan Rank Gamifikasi seluruh karyawan.</p>
          </div>
          <span class="p-input-icon-left">
            <i class="pi pi-search" />
            <InputText v-model="searchQuery" @input="onSearch" placeholder="Cari ID atau Nama..." class="w-64" />
          </span>
        </div>

        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-2">
          <DataTable :value="users" :loading="loading" paginator :rows="10" 
            class="p-datatable-sm" 
            rowHover>
            <template #empty>Belum ada data</template>
            
            <Column header="Peringkat" style="width: 80px">
              <template #body="{ index }">
                <span class="font-bold text-gray-400">#{{ index + 1 }}</span>
              </template>
            </Column>
            <Column field="hris_user_id" header="ID Karyawan"></Column>
            <Column field="full_name" header="Nama Karyawan">
              <template #body="{ data }">
                <span class="font-bold text-slate-700">{{ data.full_name }}</span>
              </template>
            </Column>
            <Column field="current_rank" header="Pangkat (Rank)">
              <template #body="{ data }">
                <Tag :value="data.current_rank" :severity="getRankSeverity(data.current_rank)" class="font-bold" />
              </template>
            </Column>
            <Column field="total_xp" header="Total XP" sortable>
              <template #body="{ data }">
                <span class="font-extrabold text-[#419CC3]">{{ data.total_xp }} XP</span>
              </template>
            </Column>
            <Column field="quizzes_completed" header="Kuis Selesai" sortable></Column>
            <Column header="Aksi" style="width: 120px">
              <template #body="{ data }">
                <Button icon="pi pi-pencil" text rounded severity="secondary" @click="openEditModal(data)" />
              </template>
            </Column>
          </DataTable>
        </div>
      </div>
    </main>
  </div>

  <Dialog v-model:visible="showDialog" header="Penyesuaian XP Manual" :modal="true" class="w-[450px]">
    <div class="space-y-4 pt-4">
      <div class="bg-blue-50 text-blue-800 p-3 rounded-lg text-xs font-medium flex items-start gap-2">
        <i class="pi pi-info-circle mt-0.5"></i>
        <span>Pengubahan XP manual akan mencatat Log Audit Trail. Pastikan Anda memiliki alasan yang jelas.</span>
      </div>
      
      <div class="flex flex-col gap-1">
        <label class="font-bold text-xs text-gray-700">Karyawan</label>
        <InputText :value="editData.full_name" disabled class="bg-gray-100" />
      </div>

      <div class="flex flex-col gap-1">
        <label class="font-bold text-xs text-gray-700">Total XP Baru</label>
        <InputText v-model="editData.new_xp" type="number" />
      </div>

      <div class="flex flex-col gap-1">
        <label class="font-bold text-xs text-gray-700">Alasan Perubahan (Audit Trail) <span class="text-red-500">*</span></label>
        <Textarea v-model="editData.reason" rows="3" placeholder="Contoh: Kesalahan sistem kuis pada tgl 12 Agustus" />
      </div>
    </div>
    <template #footer>
      <Button label="Batal" icon="pi pi-times" @click="showDialog = false" text />
      <Button label="Simpan Perubahan" icon="pi pi-check" @click="saveXp" severity="danger" />
    </template>
  </Dialog>
</template>
