// lms-frontend/src/views/LoginView.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();
const email = ref('');
const password = ref('');
const rememberMe = ref(false);
const showPassword = ref(false);

const isSubmitting = ref(false);
const isSuccess = ref(false);

const togglePassword = () => {
  showPassword.value = !showPassword.value;
};

const handleLogin = () => {
  isSubmitting.value = true;
  setTimeout(() => {
    isSubmitting.value = false;
    isSuccess.value = true;
    setTimeout(() => {
      router.push('/dashboard');
    }, 1000);
  }, 1500);
};
</script>

<template>
<div class="flex flex-col min-h-screen items-center justify-center bg-tertiary overflow-hidden">

  <!-- Main Content Canvas -->
  <main class="relative z-10 w-full max-w-md px-4 md:px-0">
    <!-- Brand Identity Section -->
    <div class="flex flex-col items-center mb-8">
      <div class="mb-4 flex items-center justify-center w-16 h-16 bg-primary/10 rounded-lg">
        <span class="material-symbols-outlined text-primary text-[32px]">corporate_fare</span>
      </div>
      <h1 class="text-2xl font-bold text-primary tracking-tight">TND SYSTEM</h1>
      <p class="text-sm text-text-main/70 mt-1">Kelola masa depan SDM Anda hari ini</p>
    </div>

    <!-- Login Card -->
    <div class="bg-white rounded-lg p-8 login-card-shadow border border-gray-200">
      <div class="mb-6">
        <h2 class="text-xl font-bold text-text-main">Masuk ke Akun</h2>
        <p class="text-sm text-text-main/70">Gunakan kredensial resmi perusahaan Anda</p>
      </div>

      <!-- Form -->
      <form class="space-y-6" @submit.prevent="handleLogin">
        <!-- Email Field -->
        <div class="space-y-1">
          <label class="text-sm font-semibold text-text-main flex items-center gap-1" for="email">
            <span class="material-symbols-outlined text-[16px]">alternate_email</span>
            Email Karyawan
          </label>
          <input v-model="email" class="w-full px-4 py-3 rounded-lg border border-gray-300 bg-white text-sm text-text-main placeholder:text-gray-400 input-focus-ring transition-all duration-200" id="email" placeholder="nama@perusahaan.com" required type="email"/>
        </div>

        <!-- Password Field -->
        <div class="space-y-1">
          <div class="flex justify-between items-center">
            <label class="text-sm font-semibold text-text-main flex items-center gap-1" for="password">
              <span class="material-symbols-outlined text-[16px]">lock</span>
              Kata Sandi
            </label>
            <a class="text-sm font-medium text-primary hover:underline transition-all" href="#">Lupa sandi?</a>
          </div>
          <div class="relative">
            <input v-model="password" class="w-full px-4 py-3 pr-12 rounded-lg border border-gray-300 bg-white text-sm text-text-main placeholder:text-gray-400 input-focus-ring transition-all duration-200" id="password" placeholder="••••••••" required :type="showPassword ? 'text' : 'password'"/>
            <button class="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-primary transition-colors" @click="togglePassword" type="button">
              <span class="material-symbols-outlined text-[20px]">{{ showPassword ? 'visibility_off' : 'visibility' }}</span>
            </button>
          </div>
        </div>

        <!-- Remember Me & Policy -->
        <div class="flex items-center gap-2">
          <input v-model="rememberMe" class="w-4 h-4 rounded border-gray-300 text-primary focus:ring-primary/20" id="remember" type="checkbox"/>
          <label class="text-sm font-medium text-text-main/70" for="remember">Tetap masuk di perangkat ini</label>
        </div>

        <!-- Action Button -->
        <button class="w-full h-[48px] bg-primary text-white font-bold text-sm rounded-lg hover:brightness-110 active:scale-[0.98] transition-all duration-200 flex items-center justify-center gap-2 shadow-sm" type="submit" :disabled="isSubmitting">
          <template v-if="isSubmitting">
            <span class="animate-spin material-symbols-outlined">progress_activity</span>
          </template>
          <template v-else-if="isSuccess">
            <span class="material-symbols-outlined text-[18px]">check_circle</span>
            <span>Berhasil</span>
          </template>
          <template v-else>
            <span>Masuk</span>
            <span class="material-symbols-outlined text-[18px]">login</span>
          </template>
        </button>
      </form>

      <!-- Social Login / Alternative (Subtle) -->
      <div class="mt-8 text-center space-y-6">
        <div class="relative">
          <div class="absolute inset-0 flex items-center"><div class="w-full border-t border-gray-200"></div></div>
          <div class="relative flex justify-center text-xs uppercase"><span class="bg-white px-4 text-gray-500">Atau</span></div>
        </div>
        <button class="w-full h-[48px] border border-gray-300 rounded-lg font-bold text-sm text-text-main hover:bg-gray-50 transition-all duration-200 flex items-center justify-center gap-3">
          <div class="w-5 h-5 bg-contain bg-center bg-no-repeat" style="background-image: url('https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg')"></div>
          Masuk dengan SSO Perusahaan
        </button>
      </div>
    </div>

    <!-- Footer / Legal Links -->
    <footer class="mt-8 text-center space-y-4">
      <p class="text-sm font-medium text-text-main/70">
          Belum punya akun? <a class="text-primary font-bold hover:underline" href="#">Hubungi HRD</a>
      </p>
      <div class="flex justify-center gap-6">
        <a class="text-sm font-medium text-gray-500 hover:text-text-main transition-colors" href="#">Bantuan</a>
        <a class="text-sm font-medium text-gray-500 hover:text-text-main transition-colors" href="#">Privasi</a>
        <a class="text-sm font-medium text-gray-500 hover:text-text-main transition-colors" href="#">Syarat Layanan</a>
      </div>
    </footer>
  </main>
</div>
</template>

// frontend/src/views/LoginView.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Building2, Mail, Lock, Eye, EyeOff, Loader2, CheckCircle2, LogIn } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export const LoginView: React.FC = () => {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [rememberMe, setRememberMe] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    setTimeout(() => {
      setIsSubmitting(false);
      setIsSuccess(true);
      setTimeout(() => {
        navigate('/dashboard');
      }, 1000);
    }, 1200);
  };

  return (
    <div className="flex flex-col min-h-screen items-center justify-center bg-slate-50 overflow-hidden px-4">
      <main className="relative z-10 w-full max-w-md">
        {/* Brand Header */}
        <div className="flex flex-col items-center mb-8 text-center">
          <div className="mb-4 flex items-center justify-center w-16 h-16 bg-[#419CC3]/10 rounded-2xl shadow-sm text-[#419CC3]">
            <Building2 className="w-8 h-8" />
          </div>
          <h1 className="text-2xl font-extrabold text-[#419CC3] tracking-tight">TND SYSTEM</h1>
          <p className="text-sm text-slate-500 mt-1">Kelola masa depan SDM Anda hari ini</p>
        </div>

        {/* Login Card */}
        <div className="bg-white rounded-2xl p-8 shadow-[0_8px_30px_rgb(0,0,0,0.06)] border border-slate-200">
          <div className="mb-6">
            <h2 className="text-xl font-bold text-slate-800">Masuk ke Akun</h2>
            <p className="text-sm text-slate-500">Gunakan kredensial resmi perusahaan Anda</p>
          </div>

          <form onSubmit={handleLogin} className="space-y-5">
            {/* Email */}
            <div className="space-y-1.5">
              <label className="text-sm font-semibold text-slate-700 flex items-center gap-1.5" htmlFor="email">
                <Mail className="w-4 h-4 text-slate-400" />
                Email Karyawan
              </label>
              <Input
                id="email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="nama@perusahaan.com"
                required
                className="h-11 rounded-lg border-slate-300 focus:border-[#419CC3] focus:ring focus:ring-[#419CC3]/20"
              />
            </div>

            {/* Password */}
            <div className="space-y-1.5">
              <div className="flex justify-between items-center">
                <label className="text-sm font-semibold text-slate-700 flex items-center gap-1.5" htmlFor="password">
                  <Lock className="w-4 h-4 text-slate-400" />
                  Kata Sandi
                </label>
                <a href="#" className="text-sm font-medium text-[#419CC3] hover:underline">
                  Lupa sandi?
                </a>
              </div>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  required
                  className="h-11 rounded-lg pr-10 border-slate-300 focus:border-[#419CC3] focus:ring focus:ring-[#419CC3]/20"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-[#419CC3] transition-colors"
                >
                  {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
            </div>

            {/* Remember Me */}
            <div className="flex items-center gap-2">
              <input
                id="remember"
                type="checkbox"
                checked={rememberMe}
                onChange={(e) => setRememberMe(e.target.checked)}
                className="w-4 h-4 rounded border-slate-300 text-[#419CC3] focus:ring-[#419CC3]/20 cursor-pointer"
              />
              <label htmlFor="remember" className="text-sm font-medium text-slate-600 cursor-pointer select-none">
                Tetap masuk di perangkat ini
              </label>
            </div>

            {/* Submit Button */}
            <Button
              type="submit"
              disabled={isSubmitting}
              className="w-full h-11 bg-[#419CC3] hover:bg-[#3484a6] text-white font-bold rounded-lg shadow-md transition-all flex items-center justify-center gap-2"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  <span>Memproses...</span>
                </>
              ) : isSuccess ? (
                <>
                  <CheckCircle2 className="w-5 h-5 text-white" />
                  <span>Berhasil Masuk</span>
                </>
              ) : (
                <>
                  <span>Masuk</span>
                  <LogIn className="w-4 h-4" />
                </>
              )}
            </Button>
          </form>

          {/* Social / SSO */}
          <div className="mt-8 text-center space-y-6">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-slate-200" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-white px-4 text-slate-400 font-semibold">Atau</span>
              </div>
            </div>

            <button
              type="button"
              className="w-full h-11 border border-slate-300 rounded-lg font-bold text-sm text-slate-700 hover:bg-slate-50 transition-all flex items-center justify-center gap-3 shadow-sm"
            >
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg"
                alt="Google"
                className="w-5 h-5"
              />
              Masuk dengan SSO Perusahaan
            </button>
          </div>
        </div>

        {/* Footer */}
        <footer className="mt-8 text-center space-y-4">
          <p className="text-sm font-medium text-slate-500">
            Belum punya akun?{' '}
            <a href="#" className="text-[#419CC3] font-bold hover:underline">
              Hubungi HRD
            </a>
          </p>
          <div className="flex justify-center gap-6 text-sm font-medium text-slate-400">
            <a href="#" className="hover:text-slate-600">Bantuan</a>
            <a href="#" className="hover:text-slate-600">Privasi</a>
            <a href="#" className="hover:text-slate-600">Syarat Layanan</a>
          </div>
        </footer>
      </main>
    </div>
  );
};
